feat(challenge): add image to challenge
tihlde/Lepton pull request #134
Opened 2020-09-16 15:42 UTC by olros

# feat(challenge): add image to challenge 🤳
## Description

Comments/issues:
closes #130 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-16 20:02 UTC, Zenjjim reviewed
Ayy gutten har lært seg backend jo. Du kan godt rename dette til badge.   og legge inn permissions at du kun kan se dine egne

2020-09-21 16:23 UTC, Eirsteir commented on app/content/models/user_badge.py
> +        verbose_name_plural = 'User Badges'
Perhaps a singular verbose name = "User badge" ?

2020-09-21 19:35 UTC, olros commented on app/content/models/user_badge.py
> +        verbose_name_plural = 'User Badges'
Agree 👍

2020-09-22 19:01 UTC, Eirsteir requested changes
I am impressed by your backend skills Olaf and with your rapid completion, well done! ❤️ 

I could not find any faults in your logic, but there are some things which can be simplified and/or improved.

2020-10-06 11:01 UTC, olros commented on app/content/serializers/user.py
> +        user_badges = UserBadge.objects.filter(user__user_id=obj.user_id).order_by(
Tried to do this, but ended up with something like "badges" is not in user. Please help 😅

2020-10-07 14:52 UTC, Eirsteir commented on app/content/serializers/user.py
> +        user_badges = UserBadge.objects.filter(user__user_id=obj.user_id).order_by(
For future reference, the argument is called `related_name` and not `verbose_name` 😅

2020-10-07 15:12 UTC, Eirsteir approved these changes
Nice work 😄 

Please rename your migration-files to something meaningful (remember to include the number prefix) and include the missing migrations file by running `make makemigrations`

2020-10-07 15:22 UTC, Eirsteir requested changes
I see now that you have not updated the fixtures, please do so before approval

2020-10-17 14:23 UTC, olros commented
Merget branchen `bug/fixtures` inn i denne for å klare å kjøre opp databasen og migrations.

2020-10-18 17:46 UTC, Eirsteir approved these changes
Congrats backender! ❤️

2020-10-18 19:21 UTC, Zenjjim requested changes
Før du merger ønsker jeg at du gjør migrations til en fil

2020-10-19 16:38 UTC, Zenjjim approved these changes

2020-10-19 17:44 UTC, merged