Wiki implementation
tihlde/Lepton pull request #146
Opened 2020-09-21 16:49 UTC by norgor

# Wiki implementation
## Added models, views, serializers and tests for wiki.
Link to Trello task: ...

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-22 19:29 UTC, Eirsteir reviewed
Hats off to you Norbert, this is fantastic! Your code is clean and I really appreciate that you added tests for your changes. Keep it going 😉 

Olaf, Zaim and me had a discussion on how the endpoint should look like and agreed that it should be in the form `/wiki/<slug>`, which means we will have to slugify the wikipost title and store it as a unique attribute in the model.

About the tests:

They are solid in themselves, but by utilizing pytest's features and python-support we can write simplified tests that are more pythonic and I would like you to follow the standard I have set in the event model tests.
This entails using fixtures instead of setup methods and so the use of classes are unecessary. The fixtures will then be loaded into the test context and can be passed as an argument to the test function. 
So instead of writing

```
    self.get_test_wiki_post()
``` 

You write

```
@pytest.fixture()
def wiki_post():
    return WikiPostFactory()
...
def test_xyz(wiki_post):
    assert wiki_post == xyz

```  

Here I have also used factories, which is basically a cooking recipie or shortcut for writing and creating reusable model objects with less code.

2020-09-22 19:29 UTC, Eirsteir commented on app/content/models/wiki_post.py
> +    wikipost_id = models.AutoField(primary_key=True)
I know we agreed on this field, but I think @Zenjjim wanted to start utilizing UUID-fields as primary keys instead. Zaim what do you say?

2020-09-22 19:29 UTC, Eirsteir commented on app/content/tests/test_wiki_integration.py
> +def create_test_post():
With `pytest.fixture` this can be passed directly to the test function as a parameter.

2020-09-22 19:29 UTC, Eirsteir commented on app/content/tests/test_wiki_integration.py
> +class TestWikiIntegration(APITestCase):
Sweet tests! I really like how you test for permissions as well. These are some clean tests 😄

2020-09-22 19:36 UTC, Eirsteir requested changes
Misclicked previously, see above review comment 😉

2020-09-22 21:40 UTC, Zenjjim commented on app/content/models/wiki_post.py
> +    wikipost_id = models.AutoField(primary_key=True)
I am still for UUID as a primary key. You can find an example in the Cheatsheet model.

2020-09-23 08:27 UTC, norgor commented on app/content/models/wiki_post.py
> +    wikipost_id = models.AutoField(primary_key=True)
Alright, thanks. I'll check it out.

2020-09-23 08:28 UTC, norgor commented on app/content/tests/test_wiki_integration.py
> +def create_test_post():
Ah, I see! Nice tip. I'll check it out. 👍

2020-10-08 16:35 UTC, Eirsteir approved these changes
Really solid work Norbert ⭐  You have done good work with the slug field and test suite.

To fix the github actions formatting/linting check, add this snippet to the make black command:
`--exclude migrations`

So the command in its entirety becomes:
```
black:
	docker-compose run web pipenv run black app/ ${args} --exclude migrations
```

2020-10-13 07:54 UTC, Eirsteir commented on app/content/models/wiki_post.py
> +    slug = models.SlugField(max_length=50, unique=True, null=True)
Can you try making this field the primary key and remove the current one? It is already unique so it might be redundant to have wikipost_id as pk.

2020-10-13 07:55 UTC, Eirsteir commented on app/content/views/wiki.py
> +    ordering = ["-created_at"]
You can change this on the model and remove this field 😉

2020-10-13 08:13 UTC, norgor commented on app/content/views/wiki.py
> +    ordering = ["-created_at"]
Alright, will do! 👍🏻

2020-10-13 10:44 UTC, merged