Images in tihlde drive
tihlde/Lepton pull request #147
Opened 2020-09-22 13:59 UTC by Tobbi-T

# feat(event): Upload event images to cloud
## Description
Link to Trello task: ...

Comments/issues:
I have added support for URL / Base64, and the upload function only runs if there is data in request.data["image"].
The URL to the cloud image then replaces the request.data["image"].

The drive link requires that you add /preview to get the raw image file.
The file type is hardcoded as "png" now, is that something to change?
The local temp file is just left after code execution but is overwritten for every execution. (app/util/temp/temp.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-24 11:23 UTC, Zenjjim requested changes
Great job @Tobbi-T. I see you overcame almost all of the challenges, and you are almost done. Added a few comments. Unsure if this feature should be tested as well @Eirsteir

2020-09-24 11:23 UTC, Zenjjim commented on app/util/cloudManager.py
> +    if "http" in url_or_data:
There are URL validaters for python, I would recommend to use them instead. [example](https://www.kite.com/python/answers/how-to-check-if-a-string-is-a-url-in-python)

2020-09-24 11:23 UTC, Zenjjim commented on app/util/cloudManager.py
> +    local_file_path = "app/util/temp/temp.%s" % (file_ext) #The temporary file will remain in /temp after execution.
Is the local file deleted after upload?

2020-09-24 11:23 UTC, Zenjjim commented on app/content/views/event.py
> +                request.data["image"] = upload_file(DriveFolder["EVENT"], request.data["image"], "png") #Filetype is hardcoded.
Unsure if this is a problem. Could you test with a JPEG, PNG, and SVG file and see if any problems occure

2020-09-24 11:23 UTC, Zenjjim commented on app/content/enums.py
> +class DriveFolder(ChoiceEnum):
Would like this renamed to something like "AppName" for further use. Don't you agree @Eirsteir

2020-09-24 11:23 UTC, Zenjjim commented on app/content/views/event.py
> +            if "image" in request.data:
Rewrite to request.data["image"]

2020-09-24 11:23 UTC, Zenjjim commented on app/content/views/event.py
> +            if "image" in request.data:
Same as above

2020-09-24 11:25 UTC, Tobbi-T commented on app/util/cloudManager.py
> +    local_file_path = "app/util/temp/temp.%s" % (file_ext) #The temporary file will remain in /temp after execution.
Not per now, that is why I mentioned it.

2020-09-24 11:26 UTC, Tobbi-T commented on app/content/views/event.py
> +                request.data["image"] = upload_file(DriveFolder["EVENT"], request.data["image"], "png") #Filetype is hardcoded.
SVG does not convert well, but I can look into adding support for it.

2020-09-24 11:30 UTC, Tobbi-T commented
@Zenjjim Do you want files to be deleted from drive if associated events are deleted?

2020-09-24 14:19 UTC, Eirsteir commented on app/content/enums.py
> +class DriveFolder(ChoiceEnum):
Agreed. Better to generalize it.

2020-09-24 14:23 UTC, Eirsteir commented on app/content/views/event.py
> +
Please extract these lines to a method and use it in a `update()` as well. Remember to use your new enums 😉  Filetype could also be an enum strictly speaking

2020-09-24 14:34 UTC, Eirsteir commented
I would prefer if every new PR included tests for new changes, but I think we need a better foundation.

I will approve if there are no tests for the moment @Zenjjim, until we we have proper documentation and well-written tests to go by. When that criteria is satisfied I think it is appropriate to make tests a criteria for new changes. By then the team is hopefully more comfortable with the codebase/flow, which is hopefully within a couple of weeks.

Do you agree?

2020-09-24 16:14 UTC, Tobbi-T commented on app/content/enums.py
> +class DriveFolder(ChoiceEnum):
> Would like this renamed to something like "AppName" for further use. Don't you agree

I'm not quite sure what you mean. @Zenjjim

2020-09-29 07:26 UTC, Zenjjim requested changes
Veldig bra Tobias. Nesten i mål nå. Lagt på noen få kommentarer som kommer til å rydde opp koden din litt. Husk å kjøre make format og make check

2020-09-29 07:26 UTC, Zenjjim commented on app/util/cloudManager.py
> +    except ValidationError as e:
`e` blir ikke brukt her så den kan du fjerne

2020-09-29 07:26 UTC, Zenjjim commented on app/util/cloudManager.py
> +        b64_data = url_or_data.encode("utf-8")
istedenfor å lage en boolean som du setter til  true/false, kan  du gjøre disse opreasjonene inni try/except. Du vil få samme resultat, men "cleanere" kode. 

```
try:
    validate(url_or_data)
    raw_data = requests.get(url_or_data).content
    b64_data = base64.b64encode(raw_data)
except ValidationError:
    b64_data = url_or_data.encode("utf-8")
```

2020-09-29 07:26 UTC, Zenjjim commented on app/content/views/event.py
> +        return request
Vil dette være en generell metode du bruker i alle views. aka for jobposts, event og profilbilde? Kan det da være en tanke å legge denne i cloudManager med request og enum som parameter?

2020-10-06 08:16 UTC, Tobbi-T commented
Hard coding the file type seems like a hard way to implement this. Is there any way front end could send file types with the request? That way the upload function will be a lot more flexible when it comes to file types. Thoughts @Eirsteir ?

2020-10-08 16:39 UTC, Eirsteir commented on app/util/cloudManager.py
> +def replace_data(request, key, to_dir, file_ext):
Avoid abbreviating variable names as we want them to be as clear as possible

2020-10-08 16:40 UTC, Eirsteir commented on app/util/cloudManager.py
> +        #file_ext = request.data["image_type"]
Is the image data passed in the request either a url or pure bytes? Perhaps there is a builtin class that can help us here.

2020-10-17 11:57 UTC, Eirsteir commented on app/content/views/event.py
> +            return Response({'detail': _(e)}, status=400)
Its more informative to return the error message, `e.message` than the error object. It plays better as a response detail message 😉

2020-10-19 07:07 UTC, Tobbi-T commented
After talking to front end, I have updated the code to deal with a URL to a file or files uploaded in [request.FILES](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.FILES). Right now, if a URL is passed, a file extension also has to be passed along with it.

2020-10-19 15:32 UTC, Eirsteir requested changes
Almost there now 😃  

This could be very difficult to debug and replicate, which is why we need to log failures. I also added a few comments about exception handling

2020-10-19 15:32 UTC, Eirsteir commented on app/util/cloudManager.py
> +    local_file_path = "app/util/temp/temp%s" % (file_extention)
Use the newer f-strings in both of these for cleaner code

2020-10-19 15:32 UTC, Eirsteir commented on app/util/cloudManager.py
> +    except:
This exception has got to be logged as an error it can be very difficult to spot and debug

2020-10-19 15:32 UTC, Eirsteir commented on app/util/cloudManager.py
>      except Exception as e:
Please log the error here as well 😄

2020-10-19 15:32 UTC, Eirsteir commented on app/util/cloudManager.py
> +            raise Exception(
We try to be specific when catching and raising exceptions to provide more information for the developer and the caller. This should be a ValueError which you then catch when  calling this method 😉

2020-10-19 17:27 UTC, Zenjjim requested changes
Nesten i mål nå!!!

2020-10-19 17:27 UTC, Zenjjim commented on app/util/cloudManager.py
> +        if len(share_list) > 0:
Fra [Python styleguild](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) anbefaler de bruken av [implicit booleanness](https://docs.python.org/3/library/stdtypes.html#truth-value-testing).
![image](https://user-images.githubusercontent.com/23628986/96489862-4f258d00-1240-11eb-8486-447e4718c46a.png)

Dermed vil koden se slik ut:
````
if  share_list:
  share_info = share_list[0]
else:
      ...
```

2020-10-19 17:27 UTC, Zenjjim commented on app/util/cloudManager.py
> +def replace_url_with_cloud_link(request, key, extention_key, to_dir):
Hva er `key`, kan du gi den et mer beskrivede navn

2020-10-19 17:27 UTC, Zenjjim commented on app/util/cloudManager.py
> +            f.close()
du kan flytte `f.close()`utenfor `if-else`, siden den blir brukt  i begge

2020-10-19 20:26 UTC, Tobbi-T commented on app/util/cloudManager.py
> +        if len(share_list) > 0:
Sweet :)

2020-10-20 07:29 UTC, Tobbi-T commented on app/util/cloudManager.py
> +def replace_url_with_cloud_link(request, key, extention_key, to_dir):
Hvordan fungerer `data_request_field` og `extension_request_field`? @Zenjjim 
`request.data[data_request_field]`

2020-10-20 07:33 UTC, Zenjjim commented on app/util/cloudManager.py
> +def replace_url_with_cloud_link(request, key, extention_key, to_dir):
Jeg tenkte mer konkret. Ok jeg vet det er noe data. Men hva er den dataen, er det bilde informasjon, er det bilde extention, det kan være veldig mye og det kommer ikke tydelig frem her

2020-10-20 07:38 UTC, Zenjjim requested changes

2020-10-20 07:38 UTC, Zenjjim commented on app/util/cloudManager.py
> +            oc.logout()
Dette ville jeg flyttet i en finally blokk siden den er brukt flere steder. https://www.w3schools.com/python/python_try_except.asp

2020-10-20 07:38 UTC, Zenjjim commented on app/util/cloudManager.py
> +            oc.logout()
Samme med remove folder

2020-10-22 14:39 UTC, Eirsteir commented on app/util/cloudManager.py
> +            logger.error(e.message)
Also here

2020-10-22 16:42 UTC, Eirsteir approved these changes
Beautiful Tobias 🥇

2020-10-26 18:27 UTC, merged