Feat(groups):  Added groups app and logic
tihlde/Lepton pull request #166
Opened 2020-10-07 19:15 UTC by Her0elt

Feat(groups):  Added groups app and logic
Added a groups app and started the logic for groups with model, serializer, and view.
I also moved premissions and enums to util, and fixed imports. 

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-08 16:57 UTC, Eirsteir commented on app/content/admin/admin.py
> +
Remember to register the Group model here 😉

2020-10-08 17:13 UTC, Eirsteir commented on app/group/factories/group_factory.py
> +    slug = "test_group"
This will case an IntegrityError because of a duplicate value for slug. You can solve this issue by using some of factory-boy's mechanisms for fields, such as `lazy_attribute `and `Iterator` or `Sequence`. 

Have a look at these resources: 
https://joequery.me/code/factory-boy-handle-unique-constraints/
https://factoryboy.readthedocs.io/en/stable/reference.html#sequence

2020-10-08 17:21 UTC, Eirsteir commented on app/group/factories/group_factory.py
> +    type = 1
A big point of a Factory is that it generates random, but consistent data. This means that it will generate random data for each instance, but you can always assert that they are what you expect. 

You should take a look at the official documentation https://factoryboy.readthedocs.io/en/stable/introduction.html 

For instance, the description might be 
` description = factory.Faker("sentence", nb_words=100, variable_nb_words=True)`
The type might be an `Iterable`, choosing a random type from the `GroupTypeEnum`:
`type = factory.Iterator(GroupTypeEnum)` (not sure about the syntax here, you might have to add the argument `getter=lambda c: c[?]`

The bottom line is that the tests should replicate real data as much as possible so that we can catch any bugs in the values a user might throw at us 😉

2020-10-08 17:22 UTC, Eirsteir commented on app/group/models/group.py
> +    created = models.IntegerField(null=True, blank = True)
Should this be a `DateTimeField`?

2020-10-08 17:26 UTC, Eirsteir commented on app/group/models/group.py
> +    type = EnumChoiceField(GroupType)
Can I propose something here? Add a `default=GroupType.OTHER`. 

This way we avoid the need to specify further without having to suffer from null-values in the data and information.

2020-10-08 17:30 UTC, Eirsteir commented on app/group/tests/test_group_model.py
> +    return GroupFactory()
Fantastic! Before you jump into writing your moddel tests, I would like to remind you that you do not have to test anything about the model, _except_ from your custom logic (that includes __str__)😄 

You can read more here, under 'Testing' https://docs.google.com/document/d/1ZVGBfNAlDfP8TQxVbb2VSnql0rVZs3j6YQTYc3000pA/edit?usp=sharing

2020-10-08 17:36 UTC, Eirsteir commented on app/group/views/group.py
> +    def retrieve(self, request, pk):
You can change `pk` to `slug` if you define a lookup field on the ViewSet itself

2020-10-08 17:36 UTC, Eirsteir commented on app/group/views/group.py
> +class GroupViewSet(viewsets.ModelViewSet):
I have to say, this ViewSet is very clean! 😍

2020-10-08 17:38 UTC, Eirsteir commented on app/group/views/group.py
> +            group = Group.objects.get(slug = pk)
@Zenjjim what did we conclude with about using `get_or_create(slug=slug)` again?

2020-10-08 17:40 UTC, Eirsteir commented on app/group/views/group.py
> +            if Group.objects.filter(slug = request.data["name"]).exists():
This can be simplified by using `Group.get_or_create(slug=slug)` and returning the group found/created

2020-10-08 17:41 UTC, Eirsteir commented on docker-compose.yml
> +      - "3305:3305"
Why did you change this?

2020-10-08 17:47 UTC, Eirsteir commented
I think this is great Hermann! This code is clean, understandable and simple (that is a compliment) 🤩  The comments are mostly tips and best practices, so don't worry. 

I do however not agree with the new location of permissions.py in utils. These classes are an essential part of the application and not "helpers", but I understand why you have put them there. 

What I suggest is to move them and enums.py to the top level directory (app) and plan for a future where the common permissions and enums might reside in a "common" app or a "permissions" app. Or simply keep commons in the top level directory and create new files in the sub-apps.

2020-10-08 18:11 UTC, Her0elt commented on docker-compose.yml
> +      - "3305:3305"
im going to change it back, my mysql server runs on 3306 so i just change it to 3305 so i dont have to kill the mysql process or cahnge it to sometihng else

2020-10-09 12:05 UTC, Eirsteir commented on app/group/factories/group_factory.py
> +    type = type = factory.Iterator(GroupType)
Beautiful! 😍

2020-10-09 12:06 UTC, Eirsteir commented on app/group/factories/group_factory.py
> +        lambda o, n: "%s@s%d.example.com" % (o.slug, n)
You can use the newer f-string syntax here 😉

2020-10-09 12:08 UTC, Eirsteir commented on app/group/tests/test_group_intergration.py
> +def test_retrieve_as_anonymous_user(request_factory, group):
This is the same test as above

2020-10-09 12:10 UTC, Eirsteir commented on app/group/tests/test_group_intergration.py
> +        (AdminGroup.PROMO, 403, "New Description"),
Will the new description be 'New Description' if the status code was 403 Forbidden?

2020-10-09 12:13 UTC, Eirsteir commented on app/group/tests/test_group_intergration.py
> +def test_create_makes_parent_group(request_factory, group, user):
Is this supposed to be named `test_create_makes_group_if_not_found`?

2020-10-09 12:25 UTC, Eirsteir commented on app/group/views/group.py
> +            self.permission_classes = [IsMember]
You have written tests that contradict this behaviour. IsMember checks for a token in the request and denied access if it is not found. This means that an anonymous user should not be able to list or retrieve groups, yet the two first tests asserts that this is indeed possible. 

Please try running the tests and make sure this is not the case or correct the logic.

2020-10-09 12:27 UTC, Eirsteir commented on app/group/views/group.py
> +                return Response({"detail": _("Group created")}, status=201)
I had a recent chat with Olaf, who requested that we responded with the entity/object on both create and update. You can safely return the group in the response here 😊

2020-10-09 12:31 UTC, Eirsteir commented on app/group/tests/test_group_intergration.py
> +    assert group.name == parent_name
How about a test for create when a group already exists?

2020-10-09 12:37 UTC, Eirsteir commented
The tests look great, really solid work here.

The only thing I am missing is docstrings. This makes it easier to follow along and ge a grasp of the expected behaviour is 😄 

Lastly, what do you think about placing all common code used in both apps in a new app called something like 'commons', ie common permissions (IsHS, IsMember etc), utils, basepagination, basemodel etc?

2020-10-11 13:43 UTC, Zenjjim requested changes

2020-10-11 13:43 UTC, Zenjjim commented on app/enums.py
> +    OTHER = "Annet"
Siden vi koder på engelsk, burde vel Enums også være på engelsk. f.eks. BOARD = "Styre", SUBGROUP="undergruppe"...

2020-10-11 13:43 UTC, Zenjjim commented on app/group/models/group.py
> +    created = models.DateTimeField(null=True, blank=True)
Om du importerer baseModel vil du få med created og updated

2020-10-11 13:43 UTC, Zenjjim commented on app/group/views/group.py
> +    pagination_class = BasePagination
Ønsker vi pagination for henting av gruppene?

2020-10-11 13:43 UTC, Zenjjim commented on app/group/views/group.py
> +            self.permission_classes = [IsMember]
Det er vel ønskelig at man skal kunne hente alle grupper uansett, også er det ulike mengde data avhengig om du er anon, medlem, hs etc?

2020-10-16 13:40 UTC, Eirsteir commented on app/common/enums.py
> +    SUBGROUPE = "Undergruppe"
Typo in SUBGROUP

2020-10-16 13:40 UTC, Eirsteir commented on app/group/factories/group_factory.py
> +    slug = factory.Sequence(lambda n: "Group{0}".format(n))
Use f-strings here

2020-10-16 13:40 UTC, Eirsteir commented on app/group/models/group.py
> +    contact = models.EmailField(max_length=200, null=True, blank=True)
Write the field name out in its entirety for cleaner code

2020-10-16 13:40 UTC, Eirsteir commented on app/group/models/group.py
> +    permissions = models.ManyToManyField(Permission, related_name="permission")
The related name should also be plural for consistency and cleaner code from the caller

2020-10-16 13:40 UTC, Eirsteir commented on app/group/views/group.py
> +            group = Group.objects.get(slug=slug)
I haven't tested it properly, but can you try to use `group = self.get_object()` and see if it does the job?

2020-10-16 13:40 UTC, Eirsteir commented on app/group/views/group.py
> +            group = Group.objects.get(slug=slug)
Same here as above

2020-10-16 13:40 UTC, Eirsteir commented on app/tests/test_group_intergration.py
> +    group = DjangoGroup.objects.create(name=group_name)
Can you add a comment here informing that it should be changed in the future to use our Group model?

2020-10-16 13:40 UTC, Eirsteir commented on app/tests/test_group_intergration.py
> +def get_response(request, group=None, user=None):
It would be preferable if we used APIClient instead. It provides a much cleaner and simpler implementation

2020-10-19 19:56 UTC, Eirsteir commented on app/group/models/group.py
> +    contact = models.EmailField(max_length=200, null=True, blank=True)
Ie, contact_email 👍

2020-10-26 17:24 UTC, Zenjjim commented on app/group/views/group.py
> +                {"detail": ("Gruppe eksisterer ikke")}, status=status.HTTP_404_NOT_FOUND
gruppen*

2020-10-26 17:27 UTC, Zenjjim commented on app/group/models/group.py
> +    """Model for Costum Groups"""
custom*

2020-10-26 17:30 UTC, Zenjjim commented on app/group/factories/group_factory.py
> +    group_description = factory.Faker("sentence", nb_words=100, variable_nb_words=True)
drop group_

2020-10-26 17:30 UTC, Zenjjim commented on app/group/models/group.py
> +    group_permissions = models.ManyToManyField(
-group_

2020-10-26 17:31 UTC, Zenjjim commented on app/group/serializers/group.py
> +from ..models import Group
absolute import

2020-10-26 17:31 UTC, Zenjjim commented on app/group/urls.py
> +from .views import GroupViewSet
abs imp

2020-10-26 17:32 UTC, Zenjjim commented on app/group/views/group.py
> +        if self.request.method in ["GET"]:
self.action.view

2020-10-27 07:26 UTC, Eirsteir commented on app/group/models/group.py
>          Permission, related_name="auth_permissions", blank=True
The related name should really be `groups` since we are defining how we should access the groups from the Permission side of the relationship. In the same way in Registration, we have `event = ForeignKey(..., related_name="registrations")`

2020-10-31 08:09 UTC, Eirsteir approved these changes
Really fine work you have done here 😄 I especially appreciate the effort you put into writing tests and polishing the code

2020-11-02 16:51 UTC, Zenjjim approved these changes

2020-11-02 18:26 UTC, merged