Test/registration integration
tihlde/Lepton pull request #178
Opened 2020-10-15 14:14 UTC by Eirsteir

# Add integration tests for registration
## Description
Link to Trello task: #113 

Comments/issues:

Tried not to introduce too many changes, only what was strictly necessary. Planning on a refactor of the viewset once this is through.

Changes: 
    - create returns registration on success
    - update returns registration on success
    - admins can delete registrations after sign off deadline

What is tested? (and expected)
- list:
    - event not found 
        - return 404
    - list as anonymous or member 
        - should not be allowed - 403 
    - list as admin 
        - should be allowed 
- retrieve:
    - not found 
        - return 404
    - as anonymous  
        - not allowed
    - as member 
        - only self - not implemented
    - as admin 
        - only self
- create:
    - event not found
    - user not found
        - not possible, how to test, if we should?
    - invalid data returns errors 
        - closed, no signup, registration start/end  
    - as anonymous 
        - not allowed
    - as member 
        - registered self no matter what
        - returns registration
    - as admin 
        - registers self no matter what
        - returns registration
        - should be able to register anyone - not implemented
- update: (mock send registration mail)
    - event not found 
    - user not found 
    - update when has_attended=True and request.data["has_attended"] 
        - should not update
    - registration mail send if not yet attended after update 
    - as anonymous 
        - not allowed
    - as member 
        - not allowed
    - as admin 
        - anyone 
- destroy
    - not found 
        - 404
    - as anonymous 
        - not allowed
    - as member 
        - only self
        - after sign off deadline:
            - not possible
    - as admin
        - any registration 
        - after sign off deadline: 
            - yes
    - as nok or promo  
        - only self

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [x] The PR includes the link to the relevant Trello task
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-16 11:53 UTC, Zenjjim requested changes
Beautiful work. Really enjoying how easy it is to read these tests. A few comments that should be easy to fix :D

2020-10-16 12:02 UTC, olros commented on app/content/views/registration.py
> +                return Response({"detail": registration_serializer.data}, status=201)
Stemmer, enten data eller detail: string

2020-10-16 12:29 UTC, Eirsteir commented on app/content/views/registration.py
> +                registration_serializer = RegistrationSerializer(
Det var primært for å serialize den nye registreringen, men skal se om det ikke går fint uten 👍

2020-10-16 12:34 UTC, Eirsteir commented on app/content/views/registration.py
> +                registration_serializer = RegistrationSerializer(
Inputet til serializeren er på feil format, så grunnen er at vi vil serialize det nye Registration-objektet. Testene feiler hvis man bare returnerer den "gamle" serializeren, `serializer.data`

2020-10-16 12:51 UTC, Eirsteir commented on app/tests/test_registration_integration.py
> +    "group_name", [AdminGroup.HS, AdminGroup.DEVKOM,],
Ja

2020-10-16 12:54 UTC, Eirsteir commented on app/tests/test_registration_integration.py
> +    "group_name", [AdminGroup.HS, AdminGroup.DEVKOM,],
Gjelder det for alle http-metoder også? Ser for meg at de burde ha tilgang til å administrere det

2020-10-20 07:46 UTC, Zenjjim approved these changes
Nice and clean. A couple of comments for further issues

2020-10-20 07:46 UTC, Zenjjim commented on app/content/enums.py
>      DEVKOM = "DevKom"
Chi heter index nå 😊

2020-10-20 07:53 UTC, olros commented on app/content/enums.py
>      DEVKOM = "DevKom"
Ohh, hvis det endres i backend så må det endres i frontend også så vi får tilgang til admin-panelet

2020-10-20 11:02 UTC, Eirsteir commented on app/content/enums.py
>      DEVKOM = "DevKom"
Fikser du det @olros?

2020-10-20 11:09 UTC, olros commented on app/content/enums.py
>      DEVKOM = "DevKom"
Jepp 👍

2020-10-20 12:06 UTC, merged