bug(celery): Refactor mailer and celery function
tihlde/Lepton pull request #184
Opened 2020-10-17 13:19 UTC by Zenjjim

# PR NAME
## Description
Update save/create method for better flow.
Update mailer functions

Comments/issues:
Would love to write tests for this, however I would need some help understanding how
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-18 14:19 UTC, Eirsteir requested changes
Good work celery master 🥕

2020-10-18 14:19 UTC, Eirsteir commented on app/content/signals.py
> +        print(e)
I think we should start using `logger.info` instead to prepare for actual logging. For now the logger will still log to the console

2020-10-18 14:19 UTC, Eirsteir commented on app/content/signals.py
> +    event_has_ended = event.end_date < today()
This and the one in the method below are perfect candidates for properties on the Event model 😄

2020-10-18 14:19 UTC, Eirsteir commented on app/content/signals.py
> +            event.sign_off_deadline_schedular_id = event_sign_off_deadline_schedular.apply_async(
I am just wondering about this assignment and the one above. Would we not have to save the event after both?

2020-10-18 14:33 UTC, Zenjjim commented on app/content/models/registration.py
> +            self = self.create()
Agreed, this is unnecessary

2020-10-18 14:39 UTC, Zenjjim commented on app/content/signals.py
> +        print(e)
Good idea. I mainly use if for debugging but starting to log is a good idea

2020-10-18 14:43 UTC, Zenjjim commented on app/content/signals.py
> +    event_has_ended = event.end_date < today()
Good idea

2020-10-18 14:50 UTC, Zenjjim commented on app/content/signals.py
> +            event.sign_off_deadline_schedular_id = event_sign_off_deadline_schedular.apply_async(
you are right. I totally forgot :D

2020-10-18 14:53 UTC, Zenjjim commented
1 runde QA kommentarer fikset :D

2020-10-20 12:01 UTC, Eirsteir requested changes
Super! I have only one last comment. Please take a look at it before approval😄

2020-11-06 08:38 UTC, Eirsteir approved these changes
Fantastic job moving celery and mailing logic out of the registration model! 🎉

2020-11-06 08:47 UTC, merged