fix(registration): Better ordering when swapping registrated list, an…
tihlde/Lepton pull request #186
Opened 2020-10-17 20:46 UTC by Zenjjim

…d add method for replacing when a person unregisteres

# PR NAME
## Description
Link to Trello task: ...

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-17 23:13 UTC, norgor commented on app/content/models/registration.py
> +            if len(registrations):
Consider refactoring the if statement and for loop into retrieving the first matching value from the iterator. That way you will be able to drop an if statement and even the for loop if you use next().

2020-10-17 23:13 UTC, norgor commented on app/content/models/registration.py
> +            registrations = Registration.objects.filter(
Does it make sense to refactor the filter calls into it's own function?

2020-10-17 23:13 UTC, norgor commented on app/content/models/registration.py
> +        self.is_on_wait = self.event.is_full()
so clear! nice!

2020-10-18 14:56 UTC, Eirsteir requested changes
A really welcomed feature and changes. However, the logic may seem a bit complex and I would like to see some tests for this. If you need some help writing them, I am more than happy to help you. Tests for the Registration model can be found in the branch test/user-event-model

2020-10-18 14:56 UTC, Eirsteir commented on app/content/models/event.py
> +        return (
The related name from registration could also be used here, ie `self.registrations.filter`

2020-10-18 14:56 UTC, Eirsteir commented on app/content/models/registration.py
> +            registrations = Registration.objects.filter(
Another approach is to create a simple manager for Event, in addition to the current one (`Event.objects`). Then we would have more reuse and separation of responsebilities, for instance `Event.registrations.waiting_list()` and `Event.registrations.list()` to return the waiting list and users to attend

2020-10-18 14:56 UTC, Eirsteir commented on app/content/models/registration.py
> +    def delete(self, *args, **kwargs):
This method is too long and does more than one thing. We would benefit from splitting this into several smaller methods and enforcing clean code.

2020-10-18 14:56 UTC, Eirsteir commented on app/content/models/registration.py
> +            ).order_by("created_at")
This is the default ordering of Registrations, is it not redundant?

2020-10-18 15:01 UTC, Zenjjim commented on app/content/models/registration.py
> +            if len(registrations):
would you mind to elaborate.

2020-10-18 15:24 UTC, Zenjjim commented on app/content/models/registration.py
> +            if len(registrations):
like this?: `next((registration for registration in registrations if registration.is_prioritized()), registrations[0])`

2020-10-18 15:25 UTC, Zenjjim commented on app/content/models/registration.py
> +            registrations = Registration.objects.filter(
since it's a used only here i belive its cleaner when we keep the filtering where it is used

2020-10-18 15:25 UTC, Zenjjim commented on app/content/models/registration.py
> +        self.is_on_wait = self.event.is_full()
:D

2020-10-18 15:27 UTC, Zenjjim commented on app/content/models/registration.py
> +            ).order_by("created_at")
Unfortunetly it is not the default ordering. The default ordering is the pk.

2020-10-18 15:38 UTC, Zenjjim commented on app/content/models/event.py
> +        return (
@Eirsteir Event and registration does not have a relation name

2020-10-18 15:39 UTC, Zenjjim commented on app/content/models/registration.py
> +            registrations = Registration.objects.filter(
Or just Event.waiting_list as an property?

2020-10-18 18:25 UTC, Eirsteir commented on app/content/models/event.py
> +        return Registration.objects.filter(event__pk=self.pk, is_on_wait=False)
Love this!!

So we don't have to filter on event everywhere, we can use the related name from the reverse relationship. This line then becomes `self.registrations.filter(is_on_wait=False)`

2020-10-18 18:30 UTC, Eirsteir commented on app/content/models/registration.py
> +        registration_move_to_queue.save()
Fantastic how you managed to reduce this from 18 to 6 lines while still making it cleaner 😍

2020-10-19 05:45 UTC, norgor commented on app/content/models/registration.py
> +            if len(registrations):
Yes, something like that! But i guess a default of registration[0] isn't the same as the previous code.

2020-10-20 11:23 UTC, Eirsteir requested changes
Looks good!

Please add a few simple tests for registration deletion. 

It is important that we have some test coverage for things like this.

2020-11-03 11:36 UTC, Eirsteir approved these changes
Welcome to the world of testing in Python, you did a great job! 🥇 

The comment is about semantics when using related names in a model 😊

2020-11-03 11:36 UTC, Eirsteir commented on app/content/models/event.py
> +        return self.registrations.filter(event__pk=self.pk, is_on_wait=True)
It is not necessary to filter on event__pk here, as `registrations` will be all registrations connected to this event 😉 
The same applies above and below

2020-11-03 11:59 UTC, merged