feat(badges): added completed count to serializer for badges
tihlde/Lepton pull request #192
Opened 2020-10-22 17:33 UTC by Her0elt

Completed count for badges
Added a counter for how many users has completed/owns a badge
Link to Trello task: ...

Comments/issues:
idk if i like the name of the field, but could not come up with anything better than completed_count or just count

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-22 17:43 UTC, olros requested changes
Usikker på om vi skal ha antall eller prosent som har en badge. Tror prosent hadde vært kulest

2020-10-22 17:43 UTC, olros commented on docker-compose.yml
> +      - "3305:3305"
🤪

2020-10-22 17:49 UTC, Zenjjim commented on app/content/serializers/badge.py
> +    completed_count = SerializerMethodField()
number_of_completed_badges?

2020-10-22 18:38 UTC, Zenjjim commented on app/content/serializers/badge.py
> +        user_amount = User.objects.all().count()
total_user_count

2020-10-22 18:38 UTC, Zenjjim commented on app/content/serializers/badge.py
> +        return badge_completion_count / user_amount * 100
Tror det er bedre practice å sende det som desimal tall, men om @olros vil ha det som prosent fungerer det vel

2020-10-22 18:38 UTC, Zenjjim commented on docker-compose.yml
> +      - "3305:3305"
Bruv

2020-10-22 18:41 UTC, olros commented on app/content/serializers/badge.py
> +        return badge_completion_count / user_amount * 100
Dere kan bestemme her, akkurat det samme for meg

2020-10-22 19:18 UTC, Her0elt commented on docker-compose.yml
> +      - "3305:3305"
lol mysql min er på 3306 orker ikke bytte den

2020-10-22 20:25 UTC, Eirsteir commented
Hva med global_completion_percentage eller total_completion_percentage_by_all_users?

2020-10-22 20:32 UTC, olros commented
> Et par forslag til: Hva med global_completion_percentage eller total_completion_percentage_by_all_users?

Stemmer for total_completion_percentage isåfall, må ikke bli for langt. Nærmer oss nesten maks-lengden på tweets 😄

2020-10-22 20:34 UTC, SveinJH commented
> Et par forslag til: Hva med global_completion_percentage eller total_completion_percentage_by_all_users?

Likte best global_completion_percentage egentlig, men er ikke veldig nøye om det er global eller total synes jeg

2020-10-22 20:40 UTC, Eirsteir commented
> > Et par forslag til: Hva med global_completion_percentage eller total_completion_percentage_by_all_users?
> 
> 
> 
> Stemmer for total_completion_percentage isåfall, må ikke bli for langt. Nærmer oss nesten maks-lengden på tweets 😄 

total_badge_completion_in_percentage_by_all_other_users_who_has_recieved_the_badge_in_the_tihlde_membership_system?

2020-10-22 20:43 UTC, SveinJH commented
> > > Et par forslag til: Hva med global_completion_percentage eller total_completion_percentage_by_all_users?
> > 
> > 
> > Stemmer for total_completion_percentage isåfall, må ikke bli for langt. Nærmer oss nesten maks-lengden på tweets 😄
> 
> total_badge_completion_in_percentage_by_all_other_users_who_has_recieved_the_badge_in_the_tihlde_membership_system?

Den er fin! 🥇

2020-10-23 14:45 UTC, Eirsteir approved these changes
Well done 😄

2020-10-23 14:47 UTC, olros approved these changes

2020-10-23 21:18 UTC, merged