Refactor(return details): Added return details to views, added status code enum, and imports
tihlde/Lepton pull request #194
Opened 2020-10-23 08:03 UTC by Her0elt

# Added return details to views, added status code enum, and absolute imports
## Added refactored returns in viewsadded absolute imports in all view files, and added status code enums to all responses. 

Comments/issues: We talk about refactoring the detail return messages to norwegian so that frontend could actually use them,
is this what we want

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-23 08:11 UTC, olros requested changes
And should we translate all details to Norwegian in this pr?

2020-10-23 08:11 UTC, olros commented on app/content/views/cheatsheet.py
> +                    {"detail": ("kokebok har blitt slettet")}, status=status.HTTP_200_OK
Stor k

2020-10-23 08:11 UTC, olros commented on app/content/views/event.py
> +                    {"detail": _("Could not perform update")}, status=status.HTTP_200_OK
Feil status-kode?

2020-10-23 08:40 UTC, Her0elt commented
> And should we translate all details to Norwegian in this pr?

dont think so whe should do it a couple of files at a time

2020-10-23 09:29 UTC, olros commented
![image](https://user-images.githubusercontent.com/31009729/96987193-f47f8000-1522-11eb-9fa9-87f97bb47805.png)

Hmm, får dette når jeg oppretter/oppdaterer events

2020-10-23 15:13 UTC, olros reviewed
Også fjerne punktum 😉

2020-10-23 15:13 UTC, olros commented on app/content/views/cheatsheet.py
> +                    {"detail": ("Kokebok har blitt slettet.")},
"Koken har blitt slettet"

2020-10-23 15:13 UTC, olros commented on app/content/views/cheatsheet.py
> +                {"detail": ("Ikke riktig tilatelse for å slette en kokebok.")},
"Du har ikke tillatelse til å slette en kok"

2020-10-23 15:13 UTC, olros commented on app/content/views/cheatsheet.py
> +                {"details": _("Kokebok ikke funnet.")}, status=status.HTTP_404_NOT_FOUND
"Koken ble ikke funnet"

2020-10-23 15:13 UTC, olros commented on app/content/views/event.py
> +                    {"detail": _("Kunne ikke utføre oppdatering av arrangementet.")},
"Kunne ikke oppdatere arrangementet"

2020-10-23 15:13 UTC, olros commented on app/content/views/event.py
> +            {"detail": ("Arrangementet har blitt slettet.")}, status=status.HTTP_200_OK
"Arrangementet ble slettet"

2020-10-23 15:13 UTC, olros commented on app/content/views/notification.py
> +                    {"detail": ("User successfully updated.")},
"Varslet ble oppdatert"

2020-10-23 15:13 UTC, olros commented on app/content/views/notification.py
> +            {"detail": ("Could not perform notification update")},
"Kunne ikke oppdatere varslet"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("Event does not exist.")}, status=status.HTTP_404_NOT_FOUND
"Arrangementet eksisterer ikke"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
>                  {"detail": _("Cannot access the registration for this user")},
"Du har ikke tilgang til denne arrangement-påmeldingen"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("Registration not found.")},
"Kunne ikke finne denne arrangement-påmeldingen"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("The provided event does not exist")},
"Dette arrangementet eksisterer ikke"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                        {"detail": _("User already attended")},
"Brukeren har allerede ankommet"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                    {"detail": _("Could not perform update")},
"Kunne ikke oppdatere"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("Could not find registration")},
"Kunne ikke finne arrangement-påmeldingen"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
>                          "detail": "Cannot sign user off after sign off deadline has passed."
"Du kan ikke melde deg av etter avmeldingsfristen"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                    {"detail": _("You can only unregister yourself")},
"Du kan bare melde deg selv av"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("Could not delete registration.")},
"Kunne ikke slette arrangement-påmeldingen"

2020-10-23 15:13 UTC, olros commented on app/content/views/registration.py
> +                {"detail": _("The provided event does not exist")},
"Dette arrangementet eksisterer ikke"

2020-10-23 15:13 UTC, olros commented on app/content/views/user_badge.py
> +                {"detail": "The badge could not be created"},
"Badget kunne ikke bli opprettet"

2020-10-23 15:13 UTC, olros commented on app/content/views/user_badge.py
> +                {"detail": "Could not find badge"}, status=status.HTTP_404_NOT_FOUND
"Kunne ikke finne badget"

2020-10-23 15:13 UTC, olros commented on app/content/views/user_badge.py
> +                {"detail": "Could not find User"}, status=status.HTTP_404_NOT_FOUND
"Kunne ikke finne brukeren"

2020-10-23 15:13 UTC, olros commented on app/content/views/user_badge.py
> +                    {"detail": "Badge completed."}, status=status.HTTP_200_OK
"Badge fullført!"

2020-10-23 15:13 UTC, olros commented on app/content/views/user_badge.py
> +                    {"detail": "Badge already completed."},
"Dette badget er allerede fullført"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
> +                {"detail": "Could not find user"}, status=status.HTTP_400_BAD_REQUEST
"Kunne ikke finne brukeren"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
> +                    {"detail": _("Could not perform user update")},
"Kunne ikke oppdatere brukeren"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
>                  return Response({"detail": _("User successfully updated.")})
"Brukeren ble oppdatert"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
>                          {"detail": _("Not authenticated to perform user update")},
"Du har ikke tillatelse til å oppdatere brukeren"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
> +                {"detail": _("User created")}, status=status.HTTP_201_CREATED
"Brukeren ble opprettet"

2020-10-23 15:13 UTC, olros commented on app/content/views/user.py
> +                {"detail": _("User not found.")}, status=status.HTTP_404_NOT_FOUND
"Brukeren ble ikke funnet"

2020-10-25 10:43 UTC, Eirsteir commented
Hvis vi skal begynne å sende responsen på norsk bør vi informere om det til hele teamet og informere om hvordan vi vil bruke meldingene. Jeg ønsker at vi skal bruke mer av django rest sine innebygde metoder, noe vi gjør allerede, og da må vi internationalize hele API-et. Det skal riktignok ifølge dokumentasjonen ikke være altfor komplisert, men det er greit å informere om likevel. 

Med koden i denne PR-en vil API-et i noen tilfeller returnere en engelsk melding.

2020-10-26 20:20 UTC, olros commented on app/content/views/event.py
> +            {"detail": ("Arrangementet ble slettet")}, status=status.HTTP_204_NO_CONTENT
Hvis du returnerer 204 - No content, så blir det ikke sendt med detail selv om du legger det i response, derav "No content". Så det må være en annen kode (og da er vel 200 riktig?)

2020-10-29 13:21 UTC, Eirsteir requested changes
Veldig bra innsats her Hermann, dette var deilig å se ❤️  

Ellers savnet jeg litt konsistens i metodene til viewset'ene og enkelte tilbakemeldinger i responsene.

2020-10-29 13:21 UTC, Eirsteir commented on app/content/serializers/event.py
> +        if "registration_priorities" in validated_data:
Dette bør håndteres et annet sted enn i views. Views er HTTP-interfacet vårt og skal dirigere forespørseler, så et bedre sted å gjøre dette er i serializeren og evt legge `set_registration_priorities()` på selve modellen

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/event.py
> +                {"detail": _("Kunne ikke oppdatere arrangementet")},
Fant ikke arrangementet?

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/cheatsheet.py
> +                self.perform_destroy(cheatsheet)
Nydelig at du bruker metoden til superklassen! Det hadde likevel vært fint om vi var konsistente, så vi her heller skriver `super().destroy()` slik som du har gjort i NewsViewSet

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/notification.py
> +                    {"detail": ("Varslet ble oppdatert")}, status=status.HTTP_200_OK,
Her skal vi vel returnere notifikasjonen?

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/registration.py
> +                {"detail": _("Kunne ikke finne arrangement-påmeldingen")},
Det holder å bare skrive "... påmeldingen". Det gjelder forsåvidt for alle responsene i denne klassen 😄

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/registration.py
> +                    {"detail": registration.delete()}, status=status.HTTP_200_OK
Hvis tanken er at vi skal returnere gode norske tilbakemeldinger så kan du dele opp denne return-setningen så vi først sletter og så gir en god tilbakemelding i responsen 😉

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/user.py
> +                {"detail": _("Bruker opprettet")}, status=status.HTTP_201_CREATED
Er det meningen at vi ikke returnerer brukeren her?

2020-10-29 13:21 UTC, Eirsteir commented on app/content/views/user_badge.py
> +                {"detail": "Badget kunne ikke ble opprettet"},
Usikker på norsk-engelsk grammatikken her? Er det mer naturlig å skrive "badgen"

2020-10-29 14:59 UTC, olros commented on app/content/views/user.py
> +                {"detail": _("Bruker opprettet")}, status=status.HTTP_201_CREATED
Tja, i akkurat dette tilfellet så logges ikke brukeren inn (siden han må godkjennes først). Da er det fint å heller vise en tilbakemelding kanskje?

2020-10-30 15:27 UTC, olros approved these changes

2020-10-31 13:26 UTC, Eirsteir approved these changes

2020-11-01 09:39 UTC, merged