refactor(registration): refactor registration viewset with exceptions
tihlde/Lepton pull request #195
Opened 2020-10-23 15:24 UTC by Eirsteir

## Add custom exception handling, an error mixin which converts regular exceptions to DRF exceptions and a handler which logs all api errors. Simplified the viewset by splitting methods and using more of DRF built in logic.
Link to Trello task: No task

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [x] The PR includes the link to the relevant Trello task
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-31 16:14 UTC, norgor requested changes
I really love how it looks so far! This is going to be super smooth! 😎I noted some things that could or should be changed. Nice work! 🥇

2020-10-31 16:14 UTC, norgor commented on app/content/views/registration.py
> +        if self._attempts_to_unregister_self():
This should become a guard clause such as:
```
if self._is_not_own_registration():
    raise PermissionDenied("You can only unregister yourself")

return self._unregister(registration)
```
The reason is that this should be a special case that is clearly handled on it's own.

2020-10-31 16:14 UTC, norgor commented on app/content/views/registration.py
> +            raise APIUserAlreadyAttendedEvent
did you forget to construct the class here?

2020-11-01 11:45 UTC, Eirsteir commented on app/content/models/event.py
> +        return self.sign_off_deadline < today()
I totally agree with you on this, thanks for pointing it out 😄

2020-11-01 11:48 UTC, Eirsteir commented on app/content/views/registration.py
> +    def _attempts_to_unregister_self(self):
I was a bit unsure of this name myself, but I like `is_own_registration`. It's clearer 😊

2020-11-01 11:52 UTC, Eirsteir commented on app/content/views/registration.py
> +            raise APIUserAlreadyAttendedEvent
It is a matter of semantics in Python as the exception object is implicitly created (or `()` is added with other words), but the fact that you asked shows that should be with the parantheses 😉

2020-11-01 12:26 UTC, Zenjjim commented on app/content/views/registration.py
> +        if self._user_has_already_attended_event(registration):
Brukerstory: Hvis en har ankommet et arrangement, og en annen prøver å komme inn med samme QR kode, skal det bli kastet en feil som sier "brukerene har allerede ankommet"

2020-11-01 12:29 UTC, Zenjjim approved these changes

2020-11-01 12:33 UTC, Eirsteir commented on app/content/views/registration.py
> +        if self._user_has_already_attended_event(registration):
Takk, legger inn en liten kommentar siden den har en spesiell betydning

2020-11-01 13:05 UTC, norgor commented on app/content/views/registration.py
> +            raise APIUserAlreadyAttendedEvent
Aaah! Didn't know that! I guess raise will construct it for you then. There was a PEP proposal for it in 2003, but argument against it was that current code had to be changed. [https://www.python.org/dev/peps/pep-0317/](url)

2020-11-01 13:10 UTC, norgor reviewed
Great job! 🥇

2020-11-01 13:10 UTC, norgor approved these changes
Great job! 🥇

2020-11-01 13:14 UTC, merged