test(news): add integration tests for news and cleaned up news a bit
tihlde/Lepton pull request #201
Opened 2020-10-29 15:48 UTC by Eirsteir

## Added integration tests for news endpoint and refactor news model, serializer and view a little to meet our current standards
Link to Trello task: closes #113 

Comments/issues:
I have not written any unittests, since there was little to no custom methods and logic for news.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [x] The PR includes the link to the relevant Trello task
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-30 18:04 UTC, norgor reviewed
Looks good overall! I just commented a few small things 🥇

2020-11-01 12:57 UTC, Zenjjim approved these changes

2020-11-01 12:57 UTC, Zenjjim commented on app/tests/test_news_integration.py
> +        (AdminGroup.HS, 201),
use status.HTTP

2020-11-01 12:57 UTC, Zenjjim commented on app/tests/test_news_integration.py
> +        (AdminGroup.HS, 200),
use status.HTTP

2020-11-01 13:13 UTC, norgor requested changes
Good stuff! 🍔

2020-11-01 13:14 UTC, norgor approved these changes
Sorry, I clicked wrong again... Good job! 😛

2020-11-01 13:28 UTC, merged