refactor(cheatsheet):added tests and changed some logic
tihlde/Lepton pull request #202
Opened 2020-10-30 08:34 UTC by Her0elt

# refactor cheatsheet added tests and changed some logic
## Refactored cheatsheet logic and viewset and added integration test fro the cheatsheet viewset

Comments/issues:
related to refactor cheatsheet in thilde/Kvark

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-31 14:00 UTC, Eirsteir requested changes
Digging the testing train you're on! 

While you are at it, could you translate to return messages to norwegian?

2020-11-01 12:58 UTC, Zenjjim commented on app/content/urls.py
> +    r"cheatsheet/(?P<study>[^\.]+)/(?P<grade>[^\.]+)/files",
Tror det er bedre om det er mulig å fjerne files

2020-11-03 10:41 UTC, olros approved these changes
🗒️  📓  📔  🎶

2020-11-03 13:45 UTC, Eirsteir approved these changes
Please update the endpoint url before you merge 😊

2020-11-03 13:45 UTC, Eirsteir commented on app/content/urls.py
> +    r"cheatsheet/(?P<study>[^\.]+)/(?P<grade>[^\.]+)/files",
Enig i den forsåvidt, fikser du det før du merger @Her0elt? 😄 

@olros da må nok frontend oppdatere url-en.

2020-11-03 16:38 UTC, merged