refactor(pageination): added only page nr to pageination repsonse
tihlde/Lepton pull request #203
Opened 2020-10-30 23:22 UTC by Her0elt

# refactored basepageination added only page nr to pageination repsonse
## refactored basepageination added only page nr to pageination repsonse you still access the next page my using the    
## query param page=page_nr but frontend now only get the page nr so they dont have to use a hacky method to get the page ##nr
Link to Trello task: ...

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-10-31 14:07 UTC, Eirsteir requested changes
Good work Hermann, only some minor comments this time 😉

2020-10-31 14:07 UTC, Eirsteir commented on app/content/pagination.py
> +    def get_previou_page(self):
Typo in method name 😊

2020-10-31 14:07 UTC, Eirsteir commented on app/content/pagination.py
> +        if not self.page.has_previous() or self.page.previous_page_number() < 1:
Isn't the second statement in this if-statement essentially the same as the first?

2020-11-01 11:37 UTC, Eirsteir commented on app/content/pagination.py
> +    page_size = 1
This should still be 25, shouldn't it?

2020-11-03 11:39 UTC, Eirsteir approved these changes
Looks good to me!

2021-02-10 13:48 UTC, Eirsteir commented
What is the status on this @Her0elt?

2021-02-10 13:57 UTC, Her0elt commented
@Eirsteir wating on frontend to change pageination der

2021-02-14 13:39 UTC, merged