Feat sentry
tihlde/Lepton pull request #220
Opened 2020-11-09 17:24 UTC by Omjoa001

## Proposed changes
feat(sentry): Innføre api logging via sentry

Issue number: closes 150#

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [x] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-11-09 17:42 UTC, Zenjjim requested changes
Nice bra jobbet. Et par Exceptions som ikke tregs å logge

2020-11-09 17:42 UTC, Zenjjim commented on app/common/permissions.py
> +        capture_exception(token_not_exist)
Denne trenger du ikke logge

2020-11-09 17:42 UTC, Zenjjim commented on app/content/serializers/event.py
> +            capture_exception(user_not_exist)
Denne trenger du ikke logge

2020-11-09 17:42 UTC, Zenjjim commented on app/content/serializers/event.py
> +            capture_exception(priority_not_exist)
Denne trenger du ikke logge

2020-11-09 20:25 UTC, Zenjjim approved these changes

2020-11-10 14:39 UTC, Eirsteir reviewed
This was a pleasure reviewing 😍 I am really exited for logging with Sentry!

I only have some minor comments and questions regarding what and how we log the errors 😄

2020-11-10 14:39 UTC, Eirsteir commented on app/common/drive_handler.py
> +        logger.error(make_directory_fail.message)
You can go ahead and remove this logger statement since you are using sentry 😄

2020-11-10 14:39 UTC, Eirsteir commented on app/common/drive_handler.py
> +        logger.error(value_error.message)
Same applies here, your sentry method wil handle the logging, so both are not necessary 😊

2020-11-10 14:39 UTC, Eirsteir commented on app/settings.py
> +sentry_sdk.init(
Can we add an if check here to only enable sentry logging in dev and prod? @Zenjjim @Omjoa001 is that possible without crashing the application?

2020-11-10 14:39 UTC, Eirsteir commented on app/util/exceptions.py
> +        capture_exception(exc)
I don't think this is actually necessary here as we could possibly get spammed with errors from sentry when the errors are actually the intended behaviour, for instance when raising a custom api exception. 

Was this because of the test failures?

2020-11-10 14:39 UTC, Eirsteir commented on app/util/mailer.py
> +        capture_exception(send_html_email_fail)
Lovely!

2020-11-10 14:39 UTC, Eirsteir commented on manage.py
> +        capture_exception(read_env_fail)
Will this method log to the console? If so, you can remove the print statement below 😉

2020-11-10 16:27 UTC, Zenjjim commented on app/settings.py
> +sentry_sdk.init(
this will crash. However if no key is inputet, sentry will not throw an error

2020-11-10 16:28 UTC, Zenjjim commented on app/util/exceptions.py
> +        capture_exception(exc)
there should not be a reason not to throw this. Instead we can implement filters in sentry dashboard is some exceptions are unessesary

2020-11-10 16:29 UTC, Zenjjim commented on app/util/exceptions.py
> +        capture_exception(exc)
Therefor i belive we should keep this

2020-11-10 16:29 UTC, Zenjjim commented on manage.py
> +        capture_exception(read_env_fail)
capture_exception does not log to console I belive

2020-11-10 16:34 UTC, Eirsteir commented on app/settings.py
> +sentry_sdk.init(
Nice!

2020-11-10 16:37 UTC, Eirsteir commented on app/util/exceptions.py
> +        capture_exception(exc)
All good 👍 I misunderstood how the logger and sentry were related

2020-11-10 19:31 UTC, Eirsteir commented
Well done Omer, I can't wait!

2020-11-10 19:32 UTC, Eirsteir approved these changes
Well done Omer, I can't wait!

2020-11-10 19:51 UTC, merged