feat(membership): added membership for groups
tihlde/Lepton pull request #221
Opened 2020-11-09 18:19 UTC by Her0elt

# Added the init logic for group membership 

## part of #154 

## The init logic includes Model and Serializer. The model has logic for changing the leader of a group. Also added a membership history to log unactive memberships, this is used for example when we swap leader in a group and should probably be added when we delete a membership. 

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [x] Build (`make PR`) was run locally without failures

2020-11-09 19:51 UTC, Eirsteir requested changes
The logic here looks mostly good - well done! I included some comments in attempt to make the code cleaner and address some holes in the logic 💯

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +            self.swap_leader()
Move this into a `clean` method and call `self.full_clean()` here instead to include full model validation including fields and unique fields. Read more here https://docs.djangoproject.com/en/3.1/ref/models/instances/#validating-objects

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +                raise Exception
Create a custom exception here to be more specific here and when catching it later. It also makes the code more readable and predictable for both the caller and here

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +            )
A suggestion for this: create a contructor method in `MembershipHistory`, `from_membership` where we can encapsulate this logic.

This could then be used below as well 😉

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +        except Exception:
Please be more specific when catching exceptions :)

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +    def swap_leader(self):
This should be an atomic operation in my opinion. When we decorate a method such as this where multiple objects are fetched and updated they could be done so atomically to ensure data consistency. 

We can achieve this by decorating the method with `@atomic` and using `select_for_update().get(...)` instead of `get`.

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +            previous_leader = Membership.objects.get(
If there is no leader, for instance when creating a leader for the first time, this will raise `Membership.DoesNotExist` and prohibit creation all together.

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +    def save(self, *args, **kwargs):
Instead of defining this in the save method where it is called each time a membership is saved, how about defining this in a separate method which we use when changing leadership?

2020-11-09 19:51 UTC, Eirsteir commented on app/group/serializers/membership.py
> +
I think we should restrict what information we pass in these serializers. I am not sure what fields are inluded by default by Django Rest, so you might save this for later if you feel like it 😊

2020-11-09 19:51 UTC, Eirsteir commented on app/group/serializers/membership.py
> +    """Serializer for a Group Membership"""
These docstrings are a bit redundant as their functions can be inferred from the name of the class. Do you agree?

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +            previous_leader = Membership.objects.get(
I see now that this will be caught in the except block below, but it could be made clearer and should be logged. Perhaps not caught here at all?

2020-11-09 19:51 UTC, Eirsteir commented on app/group/models/membership.py
> +        verbose_name_plural = "Memberships"
I think Django will inferr these names from the model class name 😊

2020-11-10 14:56 UTC, Eirsteir reviewed
I really appreciate these changes, you guys are so close! Great if you get the chance to address the comment, that way we can have a consistent codebase 😉 

I also have a suggestion regarding the `swap_leaders()` method in Membership: I am unsure if that is the best place to handle the exceptions as it might lead to confusion when saving a membership and perhaps unknowingly update the leadership and not knowing if it failed or not - it is currently being suppressed. 

This is also why I suggested moving it out of `save()` all together and explicitly calling it when updating a leadership. Then we can catch the exceptions and return an appropriate message/log it. 

My suggestion is therefore to move it out of `save` and not handling any error in the method itself, but wrap it elsewhere, alternatively raise a custom exception. What do you guys think?

2020-11-10 14:56 UTC, Eirsteir commented on app/group/serializers/membership.py
> +    group_info = serializers.SerializerMethodField()
This is really nice, but fortunately DRF already supports serializer relations by specifying the field and what serializer to use, like so: 
```
user = UserSerializer()
group = GroupSerializer()
```

This way the name of the field has to match the one in the model and class Meta 😉

2020-11-10 19:37 UTC, Eirsteir approved these changes
Great! I will approve now, but please have a look at the comment before merging 😅

2020-11-10 19:37 UTC, Eirsteir commented on app/group/models/membership.py
> +        previous_leader.save()
I think you have forgotten to update the new leader?

2020-11-10 19:46 UTC, Her0elt commented on app/group/models/membership.py
> +        previous_leader.save()
The update for the new leader happens in the save method

2020-11-10 19:53 UTC, Eirsteir commented on app/group/models/membership.py
> +        previous_leader.save()
That is another reason why I think this should be a standalone method and not used in `save`. It would be clearer if everything happened as a unit in this method explicitly, updating the new __and__ the old leader. We can then use this method to swap leaders instead of doing some extra logic everytime we call save on the membership (except for exception handling).

2020-11-10 19:54 UTC, Eirsteir requested changes
Please address the comments above when you have the time 😄

2020-11-10 19:57 UTC, Her0elt commented on app/group/models/membership.py
> +        previous_leader.save()
so you want to move everything to clean and not run full clean in save or?

2020-11-11 13:15 UTC, Eirsteir approved these changes
This looks very good now Hermann! I appreciate your effort on this QA ❤️

2020-11-11 13:17 UTC, merged