Feat/membership view and intergration test
tihlde/Lepton pull request #236
Opened 2021-01-19 18:30 UTC by Her0elt

## Proposed changes
Added view and intergration test for the membership endpoint

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-01-20 08:54 UTC, Eirsteir requested changes
Fantastic Hermann! I really appreciate that you are writing tests in every new PR you open and the code here is mostly good. I only have some questions about the error handling when swapping leadership and some suggestions as to simplify the viewset 😄

2021-01-20 08:54 UTC, Eirsteir commented on app/group/tests/test_membership_model.py
> +    membership = MembershipFactory(membership_type=MembershipType.LEADER, group=group)
I think it would be a bit more clear to assert that the previous membership has also been changed here. Do you agree?

2021-01-20 08:54 UTC, Eirsteir commented on app/group/tests/test_membership_model.py
> +def test_swap_leader_create_two_leaders(group):
This name is a bit misleading since the test makes sure the leader is properly swapped. Could you change it to reflect the intention better?

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +    """API endpoint for Groups"""
Remember to change the docstrings and remove the ones you do not think provides any additional value that is not clear from reading the code 😉

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +            MembershipHistory.from_membership(membership)
This line should be moved to the Membership model to keep most of the logic at the model level

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +        if is_admin_user(request):
If you alter the permission class as you have done with `retrieve` in `get_permissions`, you should be able to remove this check

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +    permission_classes = [IsNoKorPromo]
I think we need a different permission class here, something along the lines of group leaders and admin users (except for retrieve maybe). What do you guys think @Her0elt @Zenjjim ?

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +    queryset = Membership.objects.all()
Does this viewset still only list the memberships for a particular group? If you want to simplify the viewset, you can implement `get_queryset` and replace this line with `lookup_field = "user_id"`.

That way, you will also be able to remove `retrieve` from this viewset all together ;) 

Have a look at [RegistrationViewSet](https://github.com/tihlde/Lepton/blob/91e39be51554c340d15ebf77cd2170b1b8f8f9e1/app/content/views/registration.py#L13) for a similar implementation

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +                {"detail": ("Medlemskapet eksisterer ikke")},
Remember to use `gettext_lazy` (`_`) for translation 😉

2021-01-20 08:54 UTC, Eirsteir commented on makefile
> +cov:
Nice!

2021-01-20 08:54 UTC, Eirsteir commented on app/group/views/membership.py
> +            if serializer.is_valid():
If you choose to refactor as per the comment about `get_queryset` above, you will be able to reduce these lines to:
```
        membership = self.get_object()
        serializer = UpdateMembershipSerializer(
                membership, data=request.data, partial=True
        )
        serializer.is_valid(raise_exception=True)

        return super().update(request, *args, **kwargs)
```

2021-01-20 12:00 UTC, Her0elt commented on app/group/models/membership.py
> +        except ValidationError:
the try execpts here are to enable changing a member to a leader even if there is no leader in that group, and then still make a membership history entry for the old membership, and skip everything if the membership is a new membership

2021-01-20 12:12 UTC, Her0elt commented on app/group/views/membership.py
> +    permission_classes = [IsNoKorPromo]
yeah i think so too, do you want me to make it now or should we wait, and update it with memberships, and the new groups

2021-01-20 14:27 UTC, Zenjjim commented on app/group/views/membership.py
> +    permission_classes = [IsNoKorPromo]
Belive permissions should be in a sperate PR. Change it to indexhs  in the meantime

2021-01-20 14:33 UTC, Zenjjim commented on app/group/models/membership.py
> +            except Membership.DoesNotExist:
We are keeping them seperate because there is a possibility that there is no leader in a group. So the first check needs to be seprate from the second one

2021-01-20 14:34 UTC, Zenjjim commented on app/group/models/membership.py
> +        except ValidationError:
this is caught to that you are able to change expiration date of the membership :D

2021-01-20 14:35 UTC, Zenjjim commented on app/group/models/membership.py
> +        except ValidationError:
but I still belive there should be a better way of doing this

2021-01-20 15:13 UTC, Her0elt commented on makefile
> +cov:
how did i do that 🙃

2021-01-20 15:29 UTC, Her0elt commented on app/group/models/membership.py
> +        except ValidationError:
`
previous_leader = Membership.objects.select_for_update().filter(
                group=self.group, membership_type=self.membership_type).first()
            if previous_leader and previous_leader.user != self.user:
                MembershipHistory.from_membership(membership=previous_leader)
                previous_leader.membership_type = MembershipType.MEMBER
                previous_leader.save()
            current_membership = Membership.objects.select_for_update().filter(
                group=self.group, user=self.user).first()
            if current_membership: 
                MembershipHistory.from_membership(membership=current_membership)`

2021-01-20 15:29 UTC, Her0elt commented on app/group/models/membership.py
> +        except ValidationError:
`previous_leader = Membership.objects.select_for_update().filter(
                group=self.group, membership_type=self.membership_type).first()

            if previous_leader and previous_leader.user != self.user:
                MembershipHistory.from_membership(membership=previous_leader)
                previous_leader.membership_type = MembershipType.MEMBER
                previous_leader.save()

            current_membership = Membership.objects.select_for_update().filter(
                group=self.group, user=self.user).first()

            if current_membership: 
                MembershipHistory.from_membership(membership=current_membership)
`

2021-01-20 15:31 UTC, Her0elt commented on app/group/models/membership.py
> +        except ValidationError:
`
previous_leader = Membership.objects.select_for_update().filter(
            group=self.group, membership_type=self.membership_type).first()
if previous_leader and previous_leader.user != self.user:
            MembershipHistory.from_membership(membership=previous_leader)
            previous_leader.membership_type = MembershipType.MEMBER
            previous_leader.save()
current_membership = Membership.objects.select_for_update().filter(
            group=self.group, user=self.user).first()
        if current_membership: 
            MembershipHistory.from_membership(membership=current_membership)

`

2021-01-20 15:37 UTC, Her0elt commented on app/group/models/membership.py
> +        except ValidationError:
```python
        previous_leader = Membership.objects.select_for_update().filter(
            group=self.group, membership_type=self.membership_type).first()

        if previous_leader and previous_leader.user != self.user:
            MembershipHistory.from_membership(membership=previous_leader)
            previous_leader.membership_type = MembershipType.MEMBER
            previous_leader.save()

        current_membership = Membership.objects.select_for_update().filter(
            group=self.group, user=self.user).first()

        if current_membership: 
            MembershipHistory.from_membership(membership=current_membership)

```

2021-01-20 16:05 UTC, Eirsteir commented on app/group/models/membership.py
> +            except Membership.DoesNotExist:
Continuing the discussion in the thread below

2021-01-20 16:07 UTC, Eirsteir commented on app/group/models/membership.py
> +        except ValidationError:
I am not a big fan of the current way of doing it, as it gets hard to read and understand when letting (nested) exceptions control the flow like this. Therefore I think what you are suggesting here is a better solution.

2021-01-20 16:08 UTC, Eirsteir commented on app/group/views/membership.py
> +    permission_classes = [IsNoKorPromo]
Agreed

2021-01-25 18:31 UTC, Eirsteir requested changes
This is looking really good now Hermann! I am impressed over how clean and easy to understand your code and tests are ❤️ 

There are a few things I would like you to take a look at, including who should be able to view the memberships. Have a look at the issue (#154 ) and ask me if you have any questions 😄

2021-01-25 18:31 UTC, Eirsteir commented on app/tests/test_membership_intergration.py
> +def test_list_as_anonymous_user(default_client, membership):
I do not think everyone should be able to list or retrieve arbitrary memberships, only HS and group leaders should.

2021-01-25 18:31 UTC, Eirsteir commented on app/tests/test_membership_intergration.py
> +    """Tests if an anonymous user can fails to update a membership"""
This sentence is a bit strange. How about `Test that an anonymous user cannot update a membership`? 

This goes for some of the other docstrings in the tests below as well.

2021-01-25 18:31 UTC, Eirsteir commented on app/tests/test_membership_intergration.py
> +    """Tests if diffierent groups ability to update a membership """
Typo in `diffierent`

2021-01-25 18:31 UTC, Eirsteir commented on app/tests/test_membership_intergration.py
> +def test_create_member_membership(admin_user, membership):
Please add a docstring for clarification here and below :)

2021-01-25 18:31 UTC, Eirsteir commented on app/tests/test_membership_intergration.py
> +    return f"{GROUP_URL}/{membership.group.slug}/membership/{membership.user.user_id}/"
You can make use of the method above so you don't have to define it twice ;)

2021-01-25 18:31 UTC, Eirsteir commented on app/group/views/membership.py
> +            membership = Membership.objects.get_or_create(user=user, group=group)
I think you might be able to simply pass the id of the user and the group. I have not tested this, but it could be worth considering.

2021-01-25 18:31 UTC, Eirsteir commented on app/group/views/membership.py
> +            if serializer.is_valid():
Is there a reason you are checking the serializers validity in this way and not as you are doing it in `update()`?

2021-01-25 18:33 UTC, Her0elt commented on app/tests/test_membership_intergration.py
> +def test_list_as_anonymous_user(default_client, membership):
what if we want to show it on the page somewhere

2021-02-03 17:32 UTC, Eirsteir requested changes
This is coming together alright now. It is quite an extensive feature and you are doing good 🎉  

Some new issues has occured after my last review, please have a look at the comments :)

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +        user=user, group=group, membership_type=MembershipType.LEADER
You can use the `membership_leader` fixture here and access the user via that to avoid redeclaration and elements involved 😉

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +    """Tests that a group leader can create a member membership"""
Did you mean to test creating an existing membership here or a new one? When you use the factory syntax `MembershipFactory()` the object is saved automatically which means the membership in this test already exists. 

Perhaps duplicate this one to test that case and refactor this to use `MembershipFactory.build()`?

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +    response = client.put(url)
Is it deliberate to not pass any data in the request here?

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +    response = client.post(url, data=data, format="json")
Have a look at the comment for `test_create_member_membership_as_group_leader` at line 148. This membership also exists beforehand.

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +    response = client.post(url, data=data, format="json")
Have a look at the comment below.

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +        membership_type if membership_type else membership.membership_type
Clever!

2021-02-03 17:32 UTC, Eirsteir commented on app/tests/test_membership_integration.py
> +    """Tests if an anonymous user can fails to update a membership"""
Please correct this docstring and the one below

2021-02-03 17:32 UTC, Eirsteir commented on app/group/models/membership.py
> +        return super(Membership, self).delete(*args, **kwargs)
Should we rather use `super().delete(*args, **kwargs)`?

2021-02-08 20:47 UTC, Zenjjim approved these changes

2021-02-09 20:52 UTC, Eirsteir approved these changes
Beautiful @Her0elt 😍 I really appreciate the work and effort you have put into this feature!

Please consider the two comments i left for you.

2021-02-09 20:52 UTC, Eirsteir commented on app/group/views/membership.py
> +    def is_leader(self, user_id, group_slug):
I wonder if we migth be able to use `IsLeader.has_permission()` as a static method instead of this. I have not tested it out though

2021-02-09 20:52 UTC, Eirsteir commented on app/group/views/membership.py
> +            print(request.data["membership_type"])
Remove the print

2021-02-09 21:29 UTC, merged