feat(pages): Renamed wiki to pages, and made tree like logic
tihlde/Lepton pull request #242
Opened 2021-01-26 12:37 UTC by Her0elt

## Proposed changes
Renamed wiki to page, and added logic so that you can access a page by using page/page1/page2/page3/..............

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-01-26 12:38 UTC, olros commented
closes #123

2021-01-26 14:00 UTC, Zenjjim requested changes

2021-01-26 14:00 UTC, Zenjjim commented on app/content/views/page.py
> +                status=status.HTTP_404_NOT_FOUND,
Dette er vel en server feil og ikke en client feil. 5xx

2021-01-26 15:08 UTC, Her0elt commented on app/content/views/page.py
> +                        "En annen side med dette navnet eksisterer allerede i denne kategorien"
vi ble enig om kategori men er med på mappe også, hva syntes du?

2021-01-26 15:16 UTC, Her0elt commented on app/content/views/page.py
> +                status=status.HTTP_404_NOT_FOUND,
la til 500 men er ikke sikker på om det passer bra

2021-01-26 15:29 UTC, olros commented on app/content/views/page.py
> +                        "En annen side med dette navnet eksisterer allerede i denne kategorien"
Mappen er kanskje best

2021-01-27 13:36 UTC, olros commented on app/content/views/page.py
> +                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
Her er "Fant ikke siden fordi treet er ødelagt" mer passende siden vi henter og ikke lager en side

2021-01-27 13:36 UTC, olros commented on app/content/views/page.py
> +                {"detail": _("Kan ikke lage siden fordi, treet er ødelagt")},
Her er "Fant ikke siden fordi treet er ødelagt" mer passende siden vi henter og ikke lager en side

2021-01-27 13:36 UTC, olros commented on app/content/views/page.py
> +                {"detail": _("Kan ikke lage siden, fordi treet er ødelagt")},
Trenger kanskje ikke komma etter "siden"? Samme nedover

2021-01-27 15:40 UTC, Eirsteir commented on app/content/views/page.py
> +                        "En annen side med dette navnet eksisterer allerede i denne kategorien"
Liker mappe best 😊 

Er det gitt at hvis inndata er ugyldig så er det fordi en annen side allerede eksisterer?

2021-01-27 15:42 UTC, Eirsteir commented on app/content/views/page.py
> +                {"detail": _("Kan ikke lage siden, fordi treet er ødelagt")},
Denne casen burde vel strengt tatt logges, hvis noe er ødelagt og som vi må fikse?

2021-01-27 15:46 UTC, Eirsteir commented on app/content/views/page.py
> +    def tree(self, request, *args, **kwargs):
Hva er hensikten med dette endepunktet?

2021-01-27 15:46 UTC, Eirsteir commented on app/content/views/page.py
> +        except MultipleObjectsReturned:
Feil som denne burde også logges

2021-01-27 15:47 UTC, Eirsteir commented on app/tests/test_page_integration.py
> +    print(response)
Fjern prints

2021-01-27 16:06 UTC, olros commented on app/content/views/page.py
> +    def tree(self, request, *args, **kwargs):
For å kunne flytte sider til en annen plassering må vi kunne se hele treet minimert. Så istedenfor å kjøre rekursiv uthenting fra frontend så sendes det ut herfra

2021-01-27 20:52 UTC, Her0elt commented on app/content/views/page.py
> +                        "En annen side med dette navnet eksisterer allerede i denne kategorien"
ja for hvis serializeren feiler så kommer det av at du prøvde å lage en side med samme tittel som en annen siden sluggen blir en sluggyfied versjon av titelen resten av det som blir sendt i requesten må ikke være unikt

2021-01-31 14:25 UTC, Eirsteir approved these changes
Looks good to me! I find this concept you have implemented intriguing and its a great initiative @Her0elt 😍 Keep up the good work

2021-01-31 14:25 UTC, Eirsteir commented on app/content/factories/page_factory.py
> +class PageFactory(DjangoModelFactory):
You can use factory inheritance for these two factories since only one field is different 😉

2021-01-31 17:47 UTC, Zenjjim approved these changes
LGTM

2021-01-31 18:07 UTC, olros commented
Kan du legge til updated-at og created-at i serializer før du merger? Er kjekt å ha

2021-02-01 13:57 UTC, merged