feat(short-links): create short-link service
tihlde/Lepton pull request #290
Opened 2021-02-23 21:00 UTC by olros

## Proposed changes
Created a service which allows users to store url's behind short slugs. Everyone are allow to view the url behind a slug, but users can only list their own short-links. 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [x] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-02-24 21:45 UTC, Zenjjim requested changes
Bra jobba, litt pirk men ellers nice. Hva skjer om jeg lager ShortLinken med name "a"?? vil ikke det breake ting?

2021-02-24 21:45 UTC, Zenjjim commented on app/content/views/short_link.py
> +        return Response({"detail": "Linken ble slettet"}, status=status.HTTP_200_OK,)
Det er vel kun brukeren som opprettet linken som kan slette den? Da må det sjekkes for

2021-02-24 21:45 UTC, Zenjjim commented on app/content/views/short_link.py
> +        if self.request.method in ["POST"]:
og "DELETE"

2021-02-24 22:54 UTC, olros commented on app/content/views/short_link.py
> +        return Response({"detail": "Linken ble slettet"}, status=status.HTTP_200_OK,)
get_queryset sørger for at det kun er bruker som opprettet en link som kan finne den på andre måter enn retrieve. Altså blir det håndtert. Testes også for i test

2021-02-24 22:54 UTC, olros commented on app/content/views/short_link.py
> +        if self.request.method in ["POST"]:
Alle medlemmer skal kunne lage ny link, men de skal ikke kunne slette alle linker?

2021-02-24 22:56 UTC, olros commented
Bør nok legge inn blokkering av spesifikke navn som "a", "k", osv ja, men vil håndteres i next-appen uansett at arrangementer, nyheter, karriere og pages går foran

2021-02-25 08:57 UTC, Zenjjim commented
hadde jo vært greit med en tilbakemelding til brukeren kanskje at den finnes fra før av

2021-02-25 08:58 UTC, Zenjjim approved these changes

2021-02-25 12:18 UTC, Eirsteir approved these changes
Veldig bra Olaf, også med gode testfunksjoner og Clean kode💪🏻

2021-02-25 12:18 UTC, Eirsteir commented on app/content/views/short_link.py
> +        except Exception:
Vi prøver å unngå for brede except-setninger for å ikke sluke eventuelle feil/bugs. 


```suggestion
        except IntegrityError: 
```

2021-02-25 14:28 UTC, Zenjjim requested changes

2021-02-25 14:28 UTC, Zenjjim commented on app/content/views/short_link.py
> +        regex = re.compile("^(a/.*|k/.*|n/.*|(om/.*)|a|k|n|om)$", re.IGNORECASE)
Bedre å gjøre dette i .save metoden i modellen, Også kaste en exception 😊

2021-02-28 12:41 UTC, Zenjjim approved these changes

2021-02-28 13:03 UTC, merged