feat(permissions): implemented use of our groups and memberships in permissions
TIHLDE/Lepton pull request #30
Opened 2021-03-15 16:41 UTC by Her0elt

## Proposed changes
implemented a new way of setting permissions for the project.  Its done buy implementing functions like   
has_read_permission and has_write_permission in the model itself, then implementing DRYPermissions in the permission class  in a view. This will let us retrieve what a user has permissions to do in the app directly from the user endpoint. This is done by adding DRYGlobalPermissionsField to the user serializer. I have implemented a BaseViewPermission class, and BaseModelPermissions class which makes it easy to add what groups have the different write or read access by adding a list of the groups like this 
```python
write_access = [ list of the group names ]
read_access = [ list of the group names ]
``` 
all you need to do is to add BaseModelPermission to the class parents like so 

```python
class model(...other classes, BaseModelPermission)
```

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [x] Build (`make PR`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-03-21 17:31 UTC, Eirsteir requested changes
Nice work @Her0elt! You show high competency with handling all this complexety, well done ❤️ 

Since this is quite a change I have some quirks I would like you to address.

It also seems you might have had some git issues?

2021-03-21 17:31 UTC, Eirsteir commented on app/content/models/registration.py
> +    @staticmethod
I see there are more specific permissions for this model, how about specifying fields like `detail_write_access`, `write_access` and so on?

2021-03-21 17:31 UTC, Eirsteir commented on app/content/models/user.py
> +    return User.objects.get(user_id=userToken.user_id)
This method is a duplicated in app/common/permissions.py?

2021-03-21 17:31 UTC, Eirsteir commented on app/group/migrations/0004_auto_20210223_2003.py
> +class Migration(migrations.Migration):
Can you rename this migration file?

2021-03-21 17:31 UTC, Eirsteir commented on app/group/models/membership.py
> +        except KeyError:
These two clauses can be combined into one

2021-03-21 17:31 UTC, Eirsteir commented on app/tests/content/test_event_integration.py
> +    Membership.objects.create(group=group, user=user)
Should the factories be used here? Do we need the `Auth_group` as well?

2021-03-21 18:00 UTC, Her0elt commented on app/common/permissions.py
> +                if str(membership.group_id).lower() == str(name).lower():
that wont work since you wont check all the groups inn access and all the membships in membership, if im understanding you correctly

2021-03-21 18:04 UTC, Her0elt commented on app/content/models/notification.py
> +        if request.method == "PUT":
there arent any as i can find but ill make some

2021-03-22 15:31 UTC, Eirsteir commented on app/common/permissions.py
> +                if str(membership.group_id).lower() == str(name).lower():
My bad 😅

2021-03-24 20:29 UTC, Eirsteir requested changes
Solid arbeid Hermann, dette er clean kode og du har en gjennomgående godt struktur som og følger mønsteret du har bestemt deg for å skrive koden i. Meget bra! 😄 

Denne ble litt større enn forventet og jeg har prøvd å holde styr på hva som skjer, så rett meg hvis du må!

2021-03-24 20:29 UTC, Eirsteir commented on app/content/models/notification.py
> +        return True
```suggestion
        return request.user is not None
```

2021-03-24 20:29 UTC, Eirsteir commented on app/content/models/registration.py
> +        if self.user.user_id == get_user_id(request):
Blir disse kalt før eller etter sjekkene i viewet? Bare greit å vite at ikke denne blokker noe av det andre 😄

2021-03-24 20:29 UTC, Eirsteir commented on app/content/views/cheatsheet.py
> -            return Response(
Var det meningen å fjerne denne? Er fortsatt greit å returnere feilene på data innsendt

2021-03-24 20:29 UTC, Eirsteir commented on app/group/migrations/0004_auto_20210223_2003.py
> +# Generated by Django 3.1.7 on 2021-02-23 20:03
Hvis denne er regenerert så er det mulig vi får inconsistent migration history når vi migrerer, stemmer det?

2021-03-24 20:29 UTC, Eirsteir commented on app/group/models/membership.py
> +            ).is_leader() or super().has_write_permission(request)
Denne er tung og kompleks, kan du skrive den om til å bli mer lesbar og clean?

2021-03-24 20:29 UTC, Eirsteir commented on app/settings.py
> -    "polymorphic",
Denne må ikke fjernes

2021-03-24 20:29 UTC, Eirsteir commented on app/util/test_utils.py
> +    user.groups.add(auth_group)
Her skjer det noe rart, trodde vi ikke trengte å bruke `Auth_group` lenger?

2021-03-26 11:56 UTC, Her0elt commented on app/group/migrations/0004_auto_20210223_2003.py
> +# Generated by Django 3.1.7 on 2021-02-23 20:03
dette er ikke endret selv er auto generert av django på nytt i denne pren

2021-04-11 11:11 UTC, Eirsteir commented on app/group/migrations/0004_auto_20210223_2003.py
> +# Generated by Django 3.1.7 on 2021-02-23 20:03
Okei, men den er _ny_ i denne pr'en?

2021-04-11 11:15 UTC, Eirsteir reviewed
Dette ser veldig bra ut! Kommer til å godkjenne når du har fått løst [denne](https://github.com/TIHLDE/Lepton/pull/30#discussion_r600845718) kommentaren 😄

2021-04-12 18:02 UTC, Eirsteir approved these changes
🥳

2021-04-17 10:58 UTC, merged