feat(group): many-to-many relation between groups and users
TIHLDE/Lepton pull request #389
Opened 2022-01-20 18:14 UTC by Omjoa001

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #87 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)
- [ x ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ x ] Format and lint (`make format` and `make flake8`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-01-20 20:27 UTC, olros approved these changes
Bør vi ha tilsvarende for membership histories også?

2022-01-20 20:27 UTC, olros commented on app/group/models/group.py
> +        verbose_name="group members",
Stor G?
```suggestion
        verbose_name="Group members",
```

2022-01-27 18:28 UTC, olros requested changes
Slett begge de 2 migrasjonene og kjør `make migrations` igjen

2022-02-03 16:29 UTC, Omjoa001 commented
> Slett begge de 2 migrasjonene og kjør `make migrations` igjen

done

2022-02-03 17:00 UTC, olros approved these changes

2022-02-03 17:05 UTC, merged