feat(user): Super user can now delete users
TIHLDE/Lepton pull request #390
Opened 2022-01-21 09:29 UTC by Her0elt

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] Format and lint (`make format` and `make flake8`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-01-21 09:31 UTC, olros commented
Blir det lagd et nytt logg innlegg der det står hva som har blitt slettet?

2022-01-21 09:38 UTC, Her0elt commented
![image](https://user-images.githubusercontent.com/60223374/150503663-3c76b3c3-edb4-472f-98b8-bcb463222e3d.png)

2022-01-21 09:40 UTC, Her0elt commented
Events personen har laget kommer ikke med feks

![image](https://user-images.githubusercontent.com/60223374/150503972-7a307332-a2e4-4513-9c24-7c0f7ab5f634.png)

2022-01-21 09:52 UTC, olros commented
Tror denne løsningen er problematisk siden det lar oss slette hvilke som helst LogEntries. Med mindre vi kan limite sletting av LogEntry til når bruker slettes, så tror jeg en bedre løsning er å legge til et `deleted: boolean` og filtrere user queryset på `deleted=False` samt slette alle related objects slik som memberships, registrations, shortlinks, osv

2022-01-21 09:53 UTC, Her0elt commented
Da har vi jo fortsatt lagra infoen, hvis vi tenker på gdpr

2022-01-21 09:55 UTC, Her0elt commented
hva med å sette log entry til null for brukeren men entry fortsatt er der

2022-01-21 10:03 UTC, olros commented
> hva med å sette log entry til null for brukeren men entry fortsatt er der
> 
> https://stackoverflow.com/questions/46302263/how-do-i-override-the-django-admin-logentry-model
> 
> for da for vi fortsatt ta i bruk cascading som er litt nice

Det ser veldig relevant ut ja, bedre enn min løsning

2022-01-21 10:03 UTC, Her0elt commented
kan teste det å se om det funker bra

2022-01-21 11:51 UTC, Eirsteir requested changes
Ser greit ut dette, men har noen spørsmål ang det praktiske her:)

2022-01-21 11:51 UTC, Eirsteir commented on app/common/serializers.py
> +        instance = super().update(instance, validated_data)
Kan vi gjøre dette? Vil ikke denne linjen forhindre at vi faktisk sletter objektene?

2022-01-21 11:51 UTC, Eirsteir commented on app/content/admin/admin.py
> +        return request.user.is_superuser
Er fortsatt litt i mot at vi skal kunne slette logginnlegg. Er det noen andre måter vi kan løse det på, feks endre på relasjonen mellom en bruker og et logginnlegg?

2022-01-21 13:29 UTC, Her0elt commented
@Eirsteir, @olros vi trenger nok litt brain stroming her, for å se hva som er best

2022-01-27 15:39 UTC, Eirsteir commented
> @Eirsteir, @olros vi trenger nok litt brainstroming her, for å se hva som er best, for er flere måter å slette bruker på

Enig der, kan sjekke ut hva som er god praksis 👍

2022-01-27 16:40 UTC, Eirsteir commented
Litt vrien den her @Her0elt. Ift GDPR så tror jeg vi enten bør anonymisere eller slette og det letteste er enten å sette brukeren til null eller slette. Ser heller ikke behovet med å beholde logginnlegg så lenge uten å ha et form for formal/begrunnelse/samtykke når de logger inn. Står mer her om GDPR ift loggdata: https://www.termsfeed.com/blog/gdpr-log-data/. Vi har mer form for aktivitet enn logg/audit, så vet ikke om denne er helt gjeldende her. 

Hvis noen skal slette en annen bruker så er det fordi noen har bedt dem eller brukeren er "ugyldig" eller fake/spam. 

På den andre siden tilbyr flere tjenester at brukere kan se tidligere handlinger eller aktivitet, altså en historie, noe som kan være det formålet. Hvis dette er formålet så føler jeg vi burde slette logginnleggene når vi sletter brukeren, da hvis noen ber om å få brukeren sin slettet så forventer man nok at all data tilknyttet brukeren din slettes. Da er vi også good guys ift personvern. Usikker på hvilke problemstillinger vi støter på ved å soft-delete brukere ift GDPR her også, men det er noe som kan utforskes. 

Tror vi kan ha en god og sunn diskusjon om dette på et møte og skape kultur for GDPR. 

TLDR; definer formålet med å ha logginnlegg og ta en vurdering derfra. Ser ikke helt behovet for å beholde de per i dag.

2022-01-28 06:20 UTC, olros requested changes

2022-01-28 06:20 UTC, olros commented on app/common/tasks.py
> +    self.logger.info("Log entries has been cleared")
```suggestion
    self.logger.info("Log entries older than 30 days have been deleted")
```

2022-01-28 06:20 UTC, olros commented on app/common/serializers.py
> +        instance = super().update(instance, validated_data)
^

2022-01-28 06:20 UTC, olros commented on app/settings.py
> +if DEBUG:
Bruk if LOCAL istedenfor slik at vi kjører på samme måte i dev og prod selv om vi i dev har debug=True

2022-01-28 06:20 UTC, olros commented on app/common/tasks.py
> +def delete_log_entries(self, *args, **kwargs):
```suggestion
def delete_old_log_entries(self, *args, **kwargs):
```

2022-01-31 08:05 UTC, olros requested changes

2022-01-31 08:05 UTC, olros commented on app/celery.py
> +        "task": "app.common.tasks.delete_log_entries",
Du må oppdatere denne også når du endret navn på funksjonen ;)

2022-01-31 21:03 UTC, olros commented on app/common/serializers.py
> +
Dette overrider en metode som ikke finnes og dermed kjører den heller ikke. Vi bør nok finne en løsning så vi også logger sletting av objekter. Har du en idé om hvordan det kan løses?

2022-01-31 22:33 UTC, olros commented on app/common/serializers.py
> +
https://gist.github.com/Bernix01/da1c1f8261b75d69dbb4fb4d3c927dad

2022-02-01 09:26 UTC, olros commented
Se https://github.com/TIHLDE/Lepton/pull/410 @Her0elt

2022-02-01 14:34 UTC, Her0elt commented
@olros er denne good nå da

2022-02-01 14:50 UTC, olros commented on app/content/admin/admin.py
> +        return True
Nå skjules slette-knappen inne på Logg-siden, men `delete_permission` er True når man sletter fra andre objekter og Logginnlegget blir slettet on cascade

2022-02-01 14:51 UTC, olros approved these changes
Funker bra nå! Kjørr @Her0elt

2022-02-01 15:09 UTC, merged