feat(events): added more filtering on events
TIHLDE/Lepton pull request #434
Opened 2022-02-10 16:23 UTC by Her0elt

## Proposed changes
added the filter fields:
- open_for_sign_up which is used to filter events that you get sign up for used like this open_for_sign_up=true
- start_date_before, start_date_after = which is a range filter for event start dates
- organizer which can show events that one group is hosting

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] Format and lint (`make format` and `make flake8`) was run locally without failures

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-02-10 17:36 UTC, trthingnes requested changes
Fix typo, then 🥇

2022-02-10 17:36 UTC, trthingnes commented on app/content/filters/event.py
> +    def filter_open_for_sing_up(self, queryset, name, value):
Tror du mente `open_for_sign_up` her.

2022-02-10 20:41 UTC, olros commented on app/content/filters/event.py
> +    start_date = DateFromToRangeFilter()
Er et edge-case her hvis du har et arrangement som starter rett før månedsskiftet og slutter rett etter. Da vil det ikke komme med i den ønskede måneden, selv om det burde det.

Men er et veeldig spesifikt case så spørs om det er verdt å bruke tid på å fikse med 2 filtre istedenfor bare dette ene

2022-02-17 18:21 UTC, olros approved these changes
yey

2022-02-17 18:28 UTC, merged