feat(forms): group members can now view form answers
TIHLDE/Lepton pull request #560
Opened 2022-04-28 16:47 UTC by Her0elt

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-04-28 19:38 UTC, olros requested changes

2022-04-28 19:38 UTC, olros commented on app/forms/models/forms.py
>  class GroupForm(Form):
Holder det ikke her å bare endre linje 184 fra:
```py
return request.user.is_leader_of(group) or check_has_access(
```
til
```py
return request.user.is_member_of(group) or check_has_access(
```
?

Da slipper man å opprette en egen permission-type og alt mulig.

2022-04-28 19:38 UTC, olros commented on app/group/models/group.py
> +        return request.user and request.user.is_member_of(self)
Se kommentar på pr i kvark som gjør at vi kan fjerne denne

2022-04-28 21:56 UTC, olros commented on app/forms/models/forms.py
>  class GroupForm(Form):
Hmm, er litt tricky dette ja. Det optimale hadde kanskje vært som i events der alle i undergrupper har tilgang, men kun leder i andre grupper. Spørs om ikke det blir relativt stress riktignok.

Er heller ikke helt fan av at vi legger til spesial-permissions. Ikke særlig lett å skjønne funksjonen dems sånn umiddelbart

2022-04-29 06:23 UTC, Her0elt commented on app/forms/models/forms.py
>  class GroupForm(Form):
ja er helt enig skal vi bare åpne helt, sånn at alle har write access. Så kan vi lage issues på å låse ned igjen hvis det blir et problem

2022-04-29 08:43 UTC, olros approved these changes

2022-04-29 09:03 UTC, merged