Fix/banners search
TIHLDE/Lepton pull request #687
Opened 2023-09-05 15:44 UTC by martcl

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Issue number: closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-09-05 19:07 UTC, thomsen85 requested changes

2023-09-05 19:07 UTC, thomsen85 commented on app/communication/views/banner.py
is_visible og is_expired burde være properties på modellen, som da vil kunne automatisk filtres på med DjangoFilterBackend

2023-09-05 20:15 UTC, martcl commented on app/communication/views/banner.py
Jeg tror jeg trenger litt flere hint for å gjøre det på måten du foreslår. DjangoFilterBackend tillater ikke å filterere på model properties (automatisk), bare på model fields. Når jeg ser rundt i koden etter eksempler så finner jeg kun filtrering på denne måten her og ikke filtrering på model properties.

2023-09-07 13:50 UTC, thomsen85 commented
https://github.com/TIHLDE/Lepton/pull/669 Tihi hadde glemt vi hadde denne

2023-09-08 07:23 UTC, martcl commented
> #669 Tihi hadde glemt vi hadde denne

Like ikke at den var så dymisk. Det var for mye logikk i frontend for å hente ut bannerene. Det eneste man trenger er å se synlige nå, tidligere synlige bannere og fremtidig synlige bannere. Bedre å gjøre den logikken i backend.

2023-10-09 14:45 UTC, merged