Feat(kontres)/initial setup
TIHLDE/Lepton pull request #720
Opened 2023-10-16 17:30 UTC by eriskjel

## Proposed changes
implemented backend for kontres
this included:
endpoints for fetching, modifying, and creating new reservations

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The fixtures have been updated if needed (for migrations)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-10-23 15:15 UTC, thomsen85 requested changes
Døds bra jobba her. 

Eneste som trekkes her er at ting er gjort på en unik måte, gjerne ta en titt på annen kode som finnes i repoet for å holde koden lik gjennom hele prosjektet

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/models/reservation.py
> +class Reservation(models.Model):
Arv fra BaseModel istedenfor

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/models/bookable_item.py
> +class BookableItem(models.Model):
Arv fra BaseModel istedenfor

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/models/__init__.py
> +from .reservation import Reservation
Disse __init__.py skal være tomme

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/migrations/0001_initial.py
Slett alle migration og kjør make migration en gang så du får kun en initial migration

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/models/reservation.py
> +        BookableItem, on_delete=models.CASCADE, related_name="reservations"
Vurder PROTECT her istedenfor CASCADE

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/models/reservation.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Denne kommer sammen med Base model om jeg husker rett

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/reservation_state.py
Bedre å kalle denne fila for enums.py slik som gjort andre steder

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/serializer/bookable_item_serializer.py
> +from ..models.bookable_item import BookableItem
prøv å unnga relative imports

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/tests/test_create_reservation.py
vi har en fil som heter conftest, her kan du definere fikstures. Slik som User finnes allerede

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/tests/test_create_reservation.py
Integrasjonstester skal i tests mappen som ligger i root

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/tests/test_edit_reservation.py
> +    client = APIClient()
Se på hvordan det er gjort på de andre integrasjons testene her

2023-10-23 15:15 UTC, thomsen85 commented on app/kontres/views/fetch_bookable_items.py
> +        queryset = BookableItem.objects.all()
ha denne queryset som et classe medlem, se på hvordan det er gjort i andre Viewset :D

2023-10-24 15:59 UTC, eriskjel commented
> Døds bra jobba her.
> 
> Eneste som trekkes her er at ting er gjort på en unik måte, gjerne ta en titt på annen kode som finnes i repoet for å holde koden lik gjennom hele prosjektet

konge skal sjekke ut, takk for svar

2023-10-25 09:31 UTC, eriskjel commented
@ConradOsvik fiksa

2023-11-13 16:03 UTC, thomsen85 commented on app/kontres/serializer/reservation_seralizer.py
> +                )
Sjekk om denn er nødvendig

2023-11-13 16:03 UTC, thomsen85 commented on app/kontres/serializer/reservation_seralizer.py
> +                )
skal ikke trenge å sjekke dette to ganger

2023-11-20 18:40 UTC, MadsNyl approved these changes
Good

2024-02-07 11:47 UTC, MadsNyl reviewed
Fiks disse. Handler mye om permissions. Jeg holder på å refaktorere permissions i egen PR, derfor jeg er pirkete. Send melding hvis du lurer på noe

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +        # Any authenticated TIHLDE member can create a reservation.
Vårt permission viewset ser etter create, update, delete og write. Du må derfor endre navnet på denne til has_create_permission

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +        )
Bruk check_has_access metoden her og send inn self.write_access. Denne metoden sjekker både om det finnes en bruker og om brukern har write access

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +    read_access = [Groups.TIHLDE]
Legg til write_access = [Groups.TIHDLE] her også

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +        return cls.has_reservation_permission(request)
return check_has_access(self.write_access, request). Det skal være default at en bruker som har write access kan oppdatere og slette. Hvis det skal være egne relger for det så definerer du dette i has_object_update og destroy. classmethod leses først, og så leses de andre metodene etterpå hvis classmehod er sann

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +        return True
return check_has_access istedenfor, der du sender inn en liste med index og HS som access som skal sjekkes

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +
Legg til classmethod for update, destroy, read, retrieve og create. Vi trenger dette for å vise permissions for brukere

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/models/bookable_item.py
> +        return self.name
Legg til classmethod med has_permission for update, destroy, retrieve, read og update

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/serializer/reservation_seralizer.py
> +            raise serializers.ValidationError("The start time cannot be in the past.")
Skriv feilmelding på norsk

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/serializer/reservation_seralizer.py
> +                            "state": "You do not have permission to change the state of the reservation."
Skriv feilmelding på norsk

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/serializer/reservation_seralizer.py
> +            raise serializers.ValidationError("end_time must be after start_time")
Skriv feilmelding på norsk

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/serializer/reservation_seralizer.py
> +                    "There is an overlapping reservation for the selected time frame."
Skriv feilmelding på norsk

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +        return Response(serializer.data)
Siden default serializer er satt til ReservationSerializer kan du fjerne denne metoden. Du gjør ingenting her som ikke allerede blir gjort.

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +            return Response({"message": "No reservations found."})
Samme her, trenger ikke denne. Dette blir gjort av seg selv.

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +                    "Du har ikke tilgang til å endre reservasjonsstatus"
Dette sjekkes vel i modellen?

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +                raise ValidationError("Ugyldig tilstand for reservasjon.")
Dette vil bli sjekket i serializern. Serializer kaster feil hvis det er ugyldig tilstand

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +            raise
Denne trenger du heller ikke å ha

2024-02-07 11:47 UTC, MadsNyl commented on app/kontres/views/reservation.py
> +        return get_object_or_404(Reservation, pk=self.kwargs.get("pk"))
Denne metoden finnes allerede fra dte som blir arvet. Fjern denne. Den innebygde django metoden gjør enten det samme eller er mer effektiv

2024-02-07 11:49 UTC, eriskjel commented on app/kontres/models/reservation.py
> +    read_access = [Groups.TIHLDE]
blir det riktig? er ikke det hele poenget med å overskrive? så jeg kan introdusere logikk slik at man kun kan endre sine egne osv? thomas mente jeg ikke skulle ha den

2024-02-07 11:52 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +    read_access = [Groups.TIHLDE]
Jo, men du  skal ha write_access i tillegg

2024-02-07 11:53 UTC, MadsNyl commented on app/kontres/models/reservation.py
> +    read_access = [Groups.TIHLDE]
så det skal være 
read_access = [Groups.TIHLDE]
write_access = [Groups.TIHLDE]

2024-02-07 12:08 UTC, eriskjel commented on app/kontres/models/reservation.py
> +        return True
men jeg må vell fortsatt sjekke om det er sin egen reservasjon? fikser check has access dette?

2024-02-07 17:01 UTC, merged